### ISSUE TITLE
angular2-router-deprecated-dependencies-not-being-loaded

### ISSUE THREAD

**Issue by a4lab2** [Urigo/meteor-angular2.0-socially#103]
i cant get the '@angular/router-deprecated' loaded in my app

**Comment by haluvibe** [comment]
me too

**Comment by a4lab2** [comment]
its now loading.....had to restart the server....and reloaded all the angular2 dependencies as in the tutorial

**Comment by kamilkisiela** [comment]
We switched to use latest `@angular/router`
