### ISSUE TITLE
error when exec "meter run android-device"

### ISSUE THREAD

**Issue by cgalvarez** [Urigo/meteor-angular2.0-socially#107]
Hi.

First of all, thank you very much for your great efforts to integrate Meteor.js with Angular2, Ionic2 and Material Design.

My problem is related to Material Design and Cordova. When executing:

```
meteor add-platform android
meteor run android-device
```

I get the error `Uncaught TypeError: Cannot read property 'appendChild' of null`.

I think the backtrace to this error is:

```
/node_modules/ng2-material/src/index.ts [104]: provide(OVERLAY_CONTAINER_TOKEN, {useValue: createOverlayContainer()})
/node_modules/ng2-material/src/index.ts [114]: export const MATERIAL_PROVIDERS = MATERIAL_BROWSER_PROVIDERS;
/imports/client/app/app.web.ts: import {MATERIAL_PROVIDERS, MATERIAL_DIRECTIVES} from 'ng2-material';
/client/main.ts [8]: `import {run as runWeb} from "../imports/client/app/app.web";
```

The last executed line invokes `createOverlayContainer()`, which access to `document` and `document.body`, but they are not ready when importing `MATERIAL_PROVIDERS`.

I can output messages to the console into the android device and debug them in my laptop next way:
- Open Chrome
- Go to `chrome://inspect`
- Click on `inspect` for WebView in localhost:12256

There I see that Cordova app stops executing when targets the previous error (stops loading next imports), and thus this fires the error `deviceready has not fired after 5 seconds`.

![screenshot](https://cloud.githubusercontent.com/assets/10707639/16088103/d8bdcfcc-3325-11e6-829f-066fdc1039cd.png)

I'm pretty newbie to Meteor.js and Angular2, so I would appreciate any help anyone could give me with this error.

Thanks in advance.

PD: The web app run without errors.
EDIT: My test app uses Meteor 1.3.3, Angular2, Material Design (ng2-material) and Ionic2 (ionic-angular). It is similar to the one at the end of the 22th step of the tutorial, but I have completely simplified it (using only the `app.web.ts` and `app.mobile.ts` files with their templates (no listings, etc.). The problem appears when importing `runWeb` in `main.ts` after executing `meteor run android-device`.

**Comment by Endtry** [comment]
Hello,

I am getting the same error with the exact situation. The app works in the browser but when running 'meteor run android-device, I am greeted with a white screen. When checking the console, the error was raised when invoking createOverlayContainer() within angular2 material core. Is there a solution for this? 

Thanks in advance.

**Comment by Endtry** [comment]
I ended up wrapping the document.body.appendChild(container); in a window.document.onload because when the app loaded on the device, the body has not fully loaded yet. This raises the error in question. I don't know if this is a angular material bug or it's on meteor end but this is a fix for now until something better comes up.

@angular2-material/core/overlay/overly-container.js

```
function createOverlayContainer() {
    var container = document.createElement('div');
    container.classList.add('md-overlay-container');
    window.document.onload = function(e) { // added window.document.onload
         document.body.appendChild(container);
    };
    return container;
}
```

**Comment by cgalvarez** [comment]
@Endtry This is not a problem neither from Meteor.js nor ng2-material. The problem is in our code itself.

When we run `meteor run android-device`, our code should only load `runMobile`. The problem is that when running a mobile client only `runMobile` should be loaded, and when running a web client only `runWeb` should be loaded. Right now, the client side loads both (and this means that loads both, ng2-material and ionic2 all time), and then use the relevant one depending on the client type.

Your solution fixes this issue in the meantime, but it's not a proper solution in the long-term, because if you update your Node.js deps through `meteor npm update` and ng2-material gets eventually updated, you will need to manually apply that fix again.

I think there are two proper approaches to solve this issue.

The first approach would be using a [conditional require](https://guide.meteor.com/structure.html#using-require) to load deps based on client type, but I haven't tried it by myself yet.

Another approach could be using Ionic2 on both sides. Since ng2-material relies on angular/material2, which is in alpha phase and has only a few components in its bag, and Ionic2 is in beta phase and provides more components, this last approach makes more sense to me. Besides, you would use one unique framework for both sides (web/mobile), so your learning curve would be faster than using both (ng2-material for web, and ionic2 for mobile).

Please, let me know about your results if you try the conditional requires approach :wink:.

**Comment by Endtry** [comment]
runMobile and runWeb does not apply to me because I am not using ionic to separate the app into two version (mobile vs web). I think it is a good solution, but I decided not to take this approach because of time constraints. The code above fixes the issue and the app is now successfully loaded on android and ios. However, the side effect is MdDialog does not work on mobile devices. (works great on web version)

**Comment by kamilkisiela** [comment]
It's a known issue justindujardin/ng2-material#257

I also created a PR for that justindujardin/ng2-material#260

**Comment by numerized** [comment]
Hi guys, I'd love to use ionic to separate the app into two version (mobile vs web).
I can't make the last repo work, @kamilkisiela any news regarding the PR ?

**Comment by Urigo** [comment]
we changed the tutorial to use `angular2-material` instead of ng2-material
