### ISSUE TITLE
ionicons not working 

### ISSUE THREAD

**Issue by teisia** [Urigo/meteor-angular2.0-socially#110]
Hi - I followed the steps on the new ionic part of the tutorial and it seems like everything is working except for the ionicons. I added the mys:font package and the fonts.json but the ionicons are coming out blank (although font errors went away after adding).

**Comment by JulianMined** [comment]
`meteor npm install ionicons`

add '@import "{}/node_modules/ionicons/dist/scss/ionicons";'
to your ionic.scss

**Comment by Urigo** [comment]
@teisia we've updated the tutorial to support the new versions.
Please open another issue if it still doesn't work for you.
thanks
