### ISSUE TITLE
google accounts authentication

### ISSUE THREAD

**Issue by puedesleerlo** [Urigo/meteor-angular2.0-socially#113]
Hello, is there any package for login into google accounts? Package  angular2-meteor-accounts-ui only works with account-password system

**Comment by ohadgk** [comment]
+1

**Comment by artmadeit** [comment]
Sorry but the package angular2-meteor-accounts-ui can't support accounts for facebook,twitter,google as mentioned by @dotansimha in https://github.com/Urigo/angular2-meteor-accounts-ui/issues/8
You can use blaze templates on angular2 to have that feature, see the link of the package in https://github.com/dotansimha/angular2-blaze-template

**Comment by Urigo** [comment]
thanks for the answer @ArthurMauricioDelgadillo 
would love community contributions for this

**Comment by idesignpixels** [comment]
Could this be added to a readme for the repo, I spent awhile trying to figure out why this wasn't working as the socially tutorial implies it will, might save others some time.

> In this section we'll look at how to:
> 
> implement security for an app using Meteor and Angular 2 API
> setup user accounts in meteor using a login and password
> **setup OAuth login for Facebook & Twitter**
> restrict access to views based on user permissions"

**Comment by Urigo** [comment]
@Lindstrom1989 can you PR for this?

**Comment by idesignpixels** [comment]
No problem, https://github.com/Urigo/angular-meteor-docs/pull/258

**Comment by Urigo** [comment]
@Lindstrom1989 thanks, I also meant PR and create those missing integrations and tutorial for them

**Comment by idesignpixels** [comment]
@Urigo The way I implemented it was to not use angular2-meteor-accounts-ui and to custom build some forms and hooks using the accounts base api, I wasn't sure if you thought it might be out of the scope of the tutorial? it might make a nice addition at the end as an extra? could be a bit much as a full replacement?

**Comment by Urigo** [comment]
maybe you could PR angular2-meteor-accounts-ui with your additions to Google Auth?

**Comment by idesignpixels** [comment]
I have no experience with creating/editing meteor plugins but will have a look.
