### ISSUE TITLE
Error 'Exception in queued task' when using pagination

### ISSUE THREAD

**Issue by n1cklarosa** [Urigo/meteor-angular2.0-socially#114]
Thanks for the amazing tutorial. You inspired me to embrace Metoer/Angular2 for a project.

I am having an issue with pagination, I followed your guide building my own app around some different needs, and I kept getting issues with pagination -  I have been trying to wrap my head around it for days. I have now cloned this project and am getting the same issues with your code. I was wondering if you can think of a reason why this could be happening? 

on Chrome I receive the following when changing to page 2 or above

> Exception in queued task: EXCEPTION: Error in ./PartiesList class PartiesList - inline template:0:862
> ORIGINAL EXCEPTION: TypeError: Cannot read property 'type' of undefined
> ORIGINAL STACKTRACE:
> TypeError: Cannot read property 'type' of undefined
>     at AppElement.detachView (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:63902:17)
>     at ViewContainerRef_.remove (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:64102:34)
>     at NgFor._bulkRemove (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:71186:37)
>     at NgFor._applyChanges (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:71151:33)
>     at NgFor.ngDoCheck (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:71137:22)
>     at DebugAppView._View_PartiesList0.detectChangesInternal (PartiesList.template.js:436:42)
>     at DebugAppView.AppView.detectChanges (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:65274:14)
>     at DebugAppView.detectChanges (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:65379:44)
>     at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:65300:19)
>     at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:65285:14)
> ERROR CONTEXT:
> [object Object]
> debug.js:41 Exception in queued task: TypeError: Cannot read property 'splice' of null
>     at MongoCursorObserver._removeAt (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124602:19)
>     at removedAt (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124580:35)
>     at http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124295:20
>     at ZoneDelegate.invoke (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166141:29)
>     at Zone.run (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166034:44)
>     at Object.removedAt (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124294:23)
>     at removed (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3745:28)
>     at self.applyChange.removed (http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3674:44)
>     at http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124295:20
>     at ZoneDelegate.invoke (http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166141:29)
> util.js:222 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

With firefox - I receive the following on start up. 

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

then this when attempting to change page

> Exception in queued task: EXCEPTION: Error in ./PartiesList class PartiesList - inline template:0:862
> ORIGINAL EXCEPTION: TypeError: view is undefined
> ORIGINAL STACKTRACE:
> require<.node_modules["@angular"].core.src.linker["element.js"]</AppElement.prototype.detachView@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:63902:1
> require<.node_modules["@angular"].core.src.linker["view_container_ref.js"]</ViewContainerRef_.prototype.remove@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:64102:20
> require<.node_modules["@angular"].common.src.directives["ng_for.js"]</NgFor.prototype._bulkRemove@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:71186:17
> require<.node_modules["@angular"].common.src.directives["ng_for.js"]</NgFor.prototype._applyChanges@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:71151:28
> require<.node_modules["@angular"].c[…] meteor.js:930:11
> Exception in queued task: require<.node_modules["angular2-meteor"].dist["mongo_cursor_observer.js"]</MongoCursorObserver.prototype._removeAt@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124602:9
> require<.node_modules["angular2-meteor"].dist["mongo_cursor_observer.js"]</MongoCursorObserver.prototype._startCursorObserver/MongoCursorObserver<.removedAt@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124580:30
> require<.node_modules["angular2-meteor"].dist["patch.js"]</wrapInZone/</<@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124295:13
> require<.node_modules["zone.js"].dist["zone.js"]/</</ZoneDelegate.prototype.invoke@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166141:20
> require<.node_modules["zone.js"].dist["zone.js"]/</</Zone.prototype.run@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166034:25
> require<.node_modules["angular2-meteor"].dist["patch.js"]</wrapInZone/<@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124294:9
> LocalCollection._observeFromObserveChanges/observeChangesCallbacks.removed@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3745:11
> LocalCollection._CachingChangeObserver/self.applyChange.removed@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3674:26
> require<.node_modules["angular2-meteor"].dist["patch.js"]</wrapInZone/</<@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124295:13
> require<.node_modules["zone.js"].dist["zone.js"]/</</ZoneDelegate.prototype.invoke@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166141:20
> require<.node_modules["zone.js"].dist["zone.js"]/</</Zone.prototype.run@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166034:25
> require<.node_modules["angular2-meteor"].dist["patch.js"]</wrapInZone/<@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:124294:9
> .observeChanges/wrapCallback/</<@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:410:11
> .runTask@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:721:11
> .flush@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:749:5
> .drain@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:757:7
> LocalCollection.prototype.resumeObservers@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:1149:3
> endUpdate@http://localhost:3000/packages/mongo.js?hash=f257f65490c0d34a164a6d8801ede96905340462:271:11
> .registerStore/</store[method]@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3613:27
> ._performWrites/<@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4457:43
> _.forEach@http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:157:13
> ._performWrites@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4457:7
> ._flushBufferedWrites@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4423:5
> ._livedata_data@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4391:7
> ._livedata_nosub@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4663:5
> Connection/onMessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3383:7
> ._launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:2736:11
> _.forEach@http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:149:7
> ._launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:2735:9
> REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:175:9
> SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:1160:5
> SockJS.prototype._didMessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:1218:13
> SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:1365:9
> require<.node_modules["zone.js"].dist["zone.js"]/</</patchProperty/desc.set/wrapFn@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166587:27
> require<.node_modules["zone.js"].dist["zone.js"]/</</ZoneDelegate.prototype.invokeTask@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166174:24
> require<.node_modules["zone.js"].dist["zone.js"]/</</Zone.prototype.runTask@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166074:29
> require<.node_modules["zone.js"].dist["zone.js"]/</</ZoneTask/this.invoke@http://localhost:3000/packages/modules.js?hash=b1c5ca0fb356f1dbb5072600431a013f0871e0a8:166241:29
>  meteor.js:930:11

thanks for your help!

**Comment by nebiljabari** [comment]
@Urigo Almost the same issue here.
The app break when I click on the pagination buttons to display a new query

FireFox console: `ORIGINAL EXCEPTION: TypeError: view is undefined`
Chrome console: `ORIGINAL EXCEPTION: TypeError: Cannot read property 'type' of undefined`

At the beginning the main page was blank than I figure out why. 
On the tuto you wrote : `let options =` instead of `this.options =` 
(and of course we have to add `options: object;` in the class init and `this.options` in the subscription argument)

If it can help:
- the ReactiveVar works fine
- I tried to use ngOnInit() instead of the constructor (Angular 2 dev advice). No success
- The `(change)` directive work, it send data to the method associate with but my `try/catch error`in the `constructor()` or `ngOnInit()` is not activate
- It seems to be a Meteor Error. When I click on the console link `meteor.js 930:11` I get :

```
if (allArgumentsOfTypeString)                                                                     
> > console.log.apply(console, [Array.prototype.join.call(arguments, " ")]);            
        else                                                                                              
          console.log.apply(console, arguments);
```

_the >> are coming from me. It's highlighted_

**Comment by sotille** [comment]
same problem here!

**Comment by nebiljabari** [comment]
@Urigo If it can help to debug, I find when you click a list link and you come-back on the main page and you click a pagination button, the n°2 for exemple, it works no more : 
`ORIGINAL EXCEPTION: TypeError: view is undefined` 

but the second error remain (by bloc of 10 times) : 
`Exception in queued task: require<.node_modules["angular2-meteor"].dist["mongo_cursor_observer.js"]` ...

**Comment by daretodave** [comment]
The issue here is that we are performing the NgFor directive on a Mongo cursor object. 

While the directive is intended for iterables, the cursor is not your typical iterable. Namely, it's intended to be iterated over once, e.g. -

```
    var myCursor = db.users.find( { type: 2 } );

    while (myCursor.hasNext()) {
        print(tojson(myCursor.next()));
    }

```

In other words, not a good match for a reactive, paging scenario with sort filters. Instead, pass an array to the directive! 

Update the parties property on the PartiesList component to be of type Array -

```
export class PartiesList extends MeteorComponent implements OnInit {
//......
    public parties: Array<Party>;
//.......
```

Then update the re-diming to fetch the records from the cursor (note: consider the search function also) -

```
//....
            this.subscribe('parties', options, () => {
                this.parties = Parties.find().fetch();
            }, true);
//....
```

The astute reader will note I sacrifice reactivity with the approach. Wrap the subscription call inside of a [NgZone Run](https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html#!#run-anchor) to make this play nicely again.

**Comment by sotille** [comment]
indeed, @daretodave, your sugestion works. 
But i can't put to work the reactivity with this 

> Wrap the subscription call inside of a NgZone Run to make this play nicely again.

can you provide some snipet of code, who works in this case (socially tutorial)?

**Comment by nebiljabari** [comment]
Thanks @daretodave for the comment but doesn't work in my case.
Plus, if we follow what it's wrote in the doc and tuto _(supposing they are up to date)_
- Zone.js is handle by 

> barbatus:angular2-runtime 
> To avoid importing reflect-metatada and zone.js

 and/or 

> Angular 2 heavily relies on some polyfills (zone.js, reflect-metadata etc). There are two ways to add them:
> 
>    • Add import 'angular2-meteor-polyfills' at the top of every file that imports Angular 2;
>    • Add barbatus:angular2-polyfills package. Since it's a package, it's loaded by Meteor before any user code.
- about the Mongo.Cursor _(from the Doc API)_

> bootstrap method provides the basic application bootstrap process, it also adds support for iterating Mongo.Cursor object withing ngFor.

@sotille what he propose I think is :

```
this.ngZone.run(() => {
   this.subscribe('parties', options, this.location.get(), () => {
        this.parties = Parties.find({}, {sort: {name: this.nameOrder.get()} });
    }, true);
});
```

remember to : 
• add at the top file `import { NgZone } from '@angular/core';`
• add in the `constructor(private ngZone: NgZone) {}`

**Comment by daretodave** [comment]
@nebiljabari Exactly right on the proposal, except missing the fetch and the autorun. The placement of options is very important -

```
    //.....
    lastSubscription: SubscriptionHandle;
    //.....

    this.autorun(() => {
        let options = {
            //....
        };
        if (this.lastSubscription != null) {
            this.lastSubscription.stop();
        }
        this.lastSubscription = this.subscribe('parties', options, this.location.get(), () => {
            const _parties = Parties.find().fetch();
            this.ngZone.runGuarded(() => {
                this.parties = _parties;
            });
        }, true);
    });

    //.....
```

Also, bummer. I was almost 100% certain on the reasoning for this error - as I was able to pinpoint the problematic logic in MongoCursorObserver. Must be missing something. 

Even stranger that it resolved sotille's and my trace and not yours.

**Comment by daretodave** [comment]
--Realized I left out some important aspects of my working example. I updated the code to reflect these.

**Comment by nebiljabari** [comment]
Apologize @daretodave your code just "rock my app" ! The mystake was coming from me :-/

Here is the code snippet if it can help :

```
export class PartiesList extends MeteorComponent implements OnInit {
  parties: Mongo.Cursor<Party>;
  pageSize: number = 10;
  curPage: ReactiveVar<number> = new ReactiveVar<number>(1);
  nameOrder: ReactiveVar<number> = new ReactiveVar<number>(1);
  partiesSize: number = 0;
  location: ReactiveVar<string> = new ReactiveVar<string>(null);

  constructor(private ngZone: NgZone) {
    super();
  }

  ngOnInit() {
    this.autorun(() => {
      let options = {
                      limit: this.pageSize,
                      skip: (this.curPage.get() - 1) * this.pageSize,
                      sort: {name: this.nameOrder.get()}
                    };

      this.subscribe('parties', options, this.location.get(), () => {
        this.ngZone.run(() => {
          this.parties = Parties.find({}, {sort: {name: this.nameOrder.get()} });
        });
      }, true);
    });

    this.autorun(() => {
      this.ngZone.run(() => {
        this.partiesSize = Counts.get('numberOfParties');
      }, true);
    });
  }
```

**Comment by daretodave** [comment]
@nebiljabari Heads up, your still calling fetch on the Parties collection. In other words, I don't believe parties is of type Mongo.Cursor in your example! 

Might mislead onlookers in to believing adding "fetch" isn't part of the solution.

**Comment by nebiljabari** [comment]
Yes @daretodave I have twisted a little bit your suggestions and if I put away `.fetch()` your code no more rock my app

When I saw this point, the second time, I remembered it was a method I've already used to obtain array from Mongo. 
Present in the Meteor Doc: http://docs.meteor.com/api/collections.html#Mongo-Cursor-fetch

**Comment by daretodave** [comment]
I understand @nebiljabari. What I meant is that the return type of fetch is an Array.

```
                    console.log(Parties.find().constructor);
                    //... function (collection, selector, options) {   

                    console.log(Parties.find().fetch().constructor);
                    //... function Array() { [native code] }
```

I was referencing that in your examples, the parties property was declared as type Mongo.Cursor

```
//....
parties: Mongo.Cursor<Party>;
//....
```

:-)

**Comment by nebiljabari** [comment]
So ... 
- the `.fetch()` method allow to pagination to work **"but"** kill all reactivity (add/remove a party) 
- if we put off `.fetch()` the reactivity is back **"but"**, like you can guess, it kill the pagination

debugging still on progress...

**Comment by admirkb** [comment]
It's not confined to pagination
 <button (click)="pageChange(1)">Click # 1</button>
  <button (click)="pageChange(2)">Click # 2</button>
will give errors.

Also searching will give the problem. I guess anything that triggers a 2nd subscription.

**Comment by admirkb** [comment]
`
 <button (click)="pageChange(1)">Click # 1</button>
  <button (click)="pageChange(2)">Click # 2</button>
`

Sorry markup went missing

**Comment by nebiljabari** [comment]
For a full reactive page with pagination and fonctional search field :

```
this.subscribe('parties', options, this.location.get(), () => {
  this.ngZone.run(() => {
    this.parties = Parties.find({}, {sort: {name: this.nameOrder.get()} });
  });
}, true);
```

_"Debugging completed" we can close this issue_
_ps: I will update the full snippet upper_

**Comment by sotille** [comment]
@nebiljabari now everything works!
Thank you!

**Comment by artmadeit** [comment]
I think that all the tutorial docs that use subscribe, autorun and call methods should be updated to don't use the true parameter (the autobind argument) following the API docs updated on https://github.com/Urigo/angular-meteor-docs/pull/187. Also, because autobind is by default to true, it isn't necessary to use `this.ngZone.run()` this move us to the initial code but bad luck we get the same errors. I also use the @nebiljabari 's snippet code above without the second `this.ngZone.run()` and it works.

I just want to pointed out that autobind in nested MeteorComponent methods (like autorun and then parties subscription) probably need to be fixed. So we don't need to explicitly use `this.ngZone.run()` on the parties subscription.

**Comment by admirkb** [comment]
I can know use my buttons successfully and searching works, but could not get pagination to work!

`<collection>.find({}); is pretty basic.`

I have many collections that I want to .find() and do not want to wrap them in   this.ngZone.run()

**Comment by Urigo** [comment]
We just updated the tutorial.
If you problem still persist or you want to add or change the explanation please submit a new issue and Pull Request
