### ISSUE TITLE
Error when I executed master project in OS X

### ISSUE THREAD

**Issue by Feldor** [Urigo/meteor-angular2.0-socially#115]
Hi,

I am started with meteor-angular and with the first tutorial have been done properly and I had no problem. But when I have tried angular 2 tutorial, I have a error and I can't fix it.

I downloaded the master app and I can't run it, I tell us the steps that I am following:

-Download the Master project.

-With the command console app, I move to folder.

-Execute: 
`$ meteor npm install`

But npm says some warning:

> npm WARN @angular/platform-browser-dynamic@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
> npm WARN @angular/platform-browser-dynamic@2.0.0-rc.1 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
> npm WARN @angular/platform-browser-dynamic@2.0.0-rc.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
> npm WARN @angular/compiler@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
> npm WARN angular2-google-maps@0.12.0 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
> npm WARN angular2-google-maps@0.12.0 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
> npm WARN angular2-google-maps@0.12.0 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
> npm WARN angular2-google-maps@0.12.0 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
> npm WARN angular2-google-maps@0.12.0 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.
> npm WARN angular2-meteor-accounts-ui@0.5.0 requires a peer of @angular/router-deprecated@^2.0.0-rc.1 but none was installed.
> npm WARN @angular2-material/checkbox@2.0.0-alpha.4 requires a peer of angular2@^2.0.0-beta.8 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular/compiler@2.0.0-rc.1 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.1 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular/router@2.0.0-rc.1 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular2-material/progress-bar@^2.0.0-alpha.4 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular2-material/progress-circle@^2.0.0-alpha.4 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular2-material/radio@^2.0.0-alpha.4 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of @angular2-material/sidenav@^2.0.0-alpha.4 but none was installed.
> npm WARN ng2-material@0.4.1 requires a peer of es6-promise@>=3.0.2 but none was installed.

I supposed that the warnings were no some problems but when I execute in command console:

`meteor`

I view the following message:

> Unable to resolve some modules:
> 
>  "@angular/router-deprecated/src/lifecycle/lifecycle_annotations_impl" in /Users/FelipeAlcaide/Desktop/meteor-angular2.0-socially-master 2/node_modules/angular2-meteor-accounts-ui/build/annotations.js
> (web.browser)
> 
> If you notice problems related to these missing modules, consider running:
> 
>  `meteor npm install --save @angular`

When I run chrome and  went to http://localhost:3000/. I received the following message in browser console.

> modules-runtime.js:439 -- Uncaught Error: Cannot find module '@angular/router-deprecated/src/lifecycle/lifecycle_annotations_impl'

How can i fix it? 

PD: I use OS X
Thanks,
Felipe

**Comment by gerrymclarnon** [comment]
Hi, I have the same problem. Thanks, gerry

**Comment by Feldor** [comment]
Hi, I fixed the problem

We should execute in master project the following:

> npm install --save @angular/router-deprecated

Regards,
Felipe

**Comment by gerrymclarnon** [comment]
Hi,

Works for me now.

Thanks, gerry

**Comment by numerized** [comment]
Have you been able to launch the app on an actual device ?? I got white screen past your explanations.
