### ISSUE TITLE
templateUrl - Template not rendered

### ISSUE THREAD

**Issue by mradzinski** [Urigo/meteor-angular2.0-socially#116]
Hi, when using templateUrl the template is not rendered at all. This has nothing to do with the cache, it just seems not to find the html file.

My code looks like:

```
@Component({
    selector: 'root',
    templateUrl: './app.html'
})
class Socially() {
}
```

using <code>import template from './app.html';</code> does work, but AFAIK imports should not be used  for templating since it'll be deprecated in a close future...

**Comment by barbatus** [comment]
@mradzinski why did you decide that it'll be deprecated in the future?

**Comment by davidbonachera** [comment]
Same here, i don't know which filePath i should use now.

I used to relate everything to my base root /. But not working anymore.

I read a bit about relatives path and they seems to be complex to resolve.

Any plan, advice on this ?

**Comment by tifeit** [comment]
I'm getting error "client/app.ts (5, 22): Cannot find module './app.html'" when trying to do
import template from './app.html';

**Comment by kamilkisiela** [comment]
@tifeit It should be fixed by Urigo/meteor-static-templates#4

**Comment by corphiloscience** [comment]
I tried adding the package mentioned by @kamilkisiela but it conflicts with one of the angular2 packages on meteor startup. Any ideas?

EDIT: Heres the exact error

 While determining active plugins:
   error: conflict: two packages included in the app (urigo:static-templates and angular2-compilers) are both
   trying to handle *.html

   While determining active plugins:
   error: conflict: two packages included in the app (urigo:static-templates and angular2-compilers) are both
   trying to handle *.html

**Comment by timohermans** [comment]
So, what is the correct way to do it?

If I have `app.html` in the client folder then

```
templateUrl: 'client/app.html' //(./app.html also  doesn't work)
```

isn't working. 

Is importing the .html really the way to go and why is the normal templateUrl not working?

**Comment by Skountz** [comment]
This worked for me few days ago :

`
templateUrl: 'app.html'
`

But (probably) after meteor update, not anymore.
However this is working for me too but throws an error:

`
import template from './app.html';
`

> client/app.ts (6, 22): Cannot find module './app.html'. 

Which is the correct way ?
templateUrl was perfect IMO...

**Comment by jalalat** [comment]
It works for me like 1 in 30 times:

`templateUrl: './app.html'`

I do not why templteUrl stopped working. It is very annoying. I have not been able to work for past 4-5 days because of this issue. Please help.

**Comment by nebiljabari** [comment]
It's linked to the @Urigo `meteor-static-templates` package now include in the `angular2-compilers` one. According to the [README](https://github.com/Urigo/angular2-meteor/blob/master/README.md) here is the proper way :

>   import template from  './foo.html';
>   import style from './foo.less';

_For info `TemplateUrl:` is only able to read absolute path (ex: 'client/imports/app/hello-world.html')_

**Comment by uri** [comment]
@nebiljabari I am not @Urigo

**Comment by Urigo** [comment]
we've updated the tutorial to use the new `urigo:static-templates` package.
closing, please open another issue if you have another problem

**Comment by diegodelfin7** [comment]
Thanks ! @netanelgilad  resolved my issue.
