### ISSUE TITLE
"insert failed: Method not found" issued if collection has not been interacted with on server.

### ISSUE THREAD

**Issue by vangorra** [Urigo/meteor-angular2.0-socially#12]
I'm not sure where this issue should go. Maybe the meteor typescript project or perhaps the meteor systemjs project. I ran into this issue during the development of my project but it's easily reproducible with this project. Your advice is appreciated.

The problem:
Until the collection object's member has been accessed on the server, the client cannot perform inserts. Instead, the client throws the error "insert failed: Method not found".

Examples where inserts work:

``` typescript
// main.ts
import {Parties} from 'collections/parties';
try {
    Parties.blah
} catch (err) {}
```

``` typescript
// main.ts
import {Parties} from 'collections/parties';
Meteor.publish('blah', function () {
    return Parties.find();
});
```

Inserts will fail with error:

``` typescript
// main.ts
import {Parties} from 'collections/parties';
```

It looks like the import statement is returning a reference to a wrapper of sorts. It's not until access to the wrapper has been made does the lower system initialize the object. What's a good way to work around this?

While not directly applicable to this application, there are many situations where we want to use a db object to keep track of user behavior and not necessarily query for it. For example, keeping track of a user's progress during a multi-page workflow, like a form. This is a situation where a user would never see the generated data but it is still persisted.

**Comment by johnalston** [comment]
@vangorra Any new insights on this?  I'm struggling with it as well.

**Comment by vangorra** [comment]
Not any more. It turns out the import path was incorrect. It's best to use relative paths.
