### ISSUE TITLE
Step 20: Cannot find module 'meteor/jalik:ufs'

### ISSUE THREAD

**Issue by janus-reith** [Urigo/meteor-angular2.0-socially#120]
I am unable to import this module properly.
I get the error Cannot find module 'meteor/jalik:ufs' in the console log.

Webstorm highlighst import { UploadFS } from 'meteor/jalik:ufs'; in my code, stating that it can't resolve the symbol UploadFS and the directory meteor in meteor/jalik:ufs.

What am I missing here? 
I tried to implement UploadFS like described here on the angular-meteor website.

I get a similiar error when I download the zip of this tutorial step.

**Comment by razordesign** [comment]
Same here, still trying to fix that.

**Comment by Urigo** [comment]
we've updated the tutorial.
Please try again and open a new issue if it still doesn't work for you.
