### ISSUE TITLE
RequireUser changed to AuthGuard in angular2-meteor-accounts-ui, breaks steps 8 +

### ISSUE THREAD

**Issue by slayerfat** [Urigo/meteor-angular2.0-socially#122]
Greetings!

in step 8 the RequireUser changed: https://github.com/Urigo/angular2-meteor-accounts-ui/commit/460dc51f9211e2a733728df2fce1280057e0323b

it seems it was updated to the new [router 3 beta 2 canActivate guard type](https://angular.io/docs/ts/latest/guide/router.html#!#can-activate-guard), this breaks the tutorial.

however it's easily fixed by adding the guard in the router config (code from step 8):

``` ts
// ...
import { AuthGuard } from 'angular2-meteor-accounts-ui';

// ...
const routes: RouterConfig = [
  {path: '', component: PartiesList},
  {path: 'party/:partyId', component: PartyDetails, canActivate: [AuthGuard]},
];

bootstrap(Socially, [
  APP_ROUTER_PROVIDERS,
  AuthGuard,
  provide(APP_BASE_HREF, {useValue: '/'})
]);
```

i would be happy to do a PR, however i don't know how to do it without breaking the tag structure :cry:

**Comment by slayerfat** [comment]
i just found out your [tutorial](https://github.com/Urigo/meteor-angular-socially/blob/master/EDIT_THIS_TUTORIAL.md) will try to learn it in the meantime and try to make a PR

**Comment by fabicious** [comment]
Thanks for finding out.

Just if maybe someone is wondering what to do with `party-details.js`: Just leave it like it was. Without `import { RequireUser } from 'angular2-meteor-accounts-ui';` and `@RequireUser()` (simply skip step 8.9).
The changes above will do the whole job instead.

**Comment by jgg3** [comment]
@slayerfat I just fixed my tutorial with this change, so thanks for posting it.  I had to hunt for where to put it though, since it wasn't mentioned above.  For anyone else, it goes in app.ts.
Step 8 was full of problems for me, but I got to the end and can now proceed.

**Comment by Urigo** [comment]
the tutorial was updated with the new changed.
Please open a new issue with something doesn't work for you
