### ISSUE TITLE
Step 6 - Error in PartyDetails - inline template

### ISSUE THREAD

**Issue by fabicious** [Urigo/meteor-angular2.0-socially#123]
After doing step 6.3 (adding `[(ngModel)]`) I'm getting this error:

![bildschirmfoto 2016-07-21 um 19 07 05](https://cloud.githubusercontent.com/assets/4696582/17031821/5cd3bdc8-4f76-11e6-927a-e4cda20029e9.png)

If I change the syntax from  `[(ngModel)]="party.name"` to `ng-model="party.name"` the console is fine.
But there still is the problem that `{{party.name}}` is always "empty". Doesn't matter what I type in the input.

I even tried it with the zip of step 7. Same problem.

Any suggestions?

**Comment by ghost** [comment]
Same error here

**Comment by nebiljabari** [comment]
This error seems to indicate that you've forgot the `*ngIf='party'` in your form tag
`<form (submit)='saveParty(party)' *ngIf='party'>`

**Comment by fabicious** [comment]
Thanks that's working for me. Should be updated in the tutorial.
Do I have to add `*ngIf` in every template I use component variables?

**Comment by nebiljabari** [comment]
The `*ngIf` directive is present in part 5.16
Not in every templates only those who don't have a init variable 

I think the simplest explanation is in the official tutorial part 3 Master/Detail :
https://angular.io/docs/ts/latest/tutorial/toh-pt2.html

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
