### ISSUE TITLE
Step 12, pagination work un-correctly

### ISSUE THREAD

**Issue by tna274** [Urigo/meteor-angular2.0-socially#127]
I was added pagination as follows in step 12, UI worked fine, but when I change page or change order of party, it's not running, no one party was showed
And in my console show Exception:

<i>
Exception in queued task: EXCEPTION: Error in ./PartiesList class PartiesList - inline template:0:393
ORIGINAL EXCEPTION: TypeError: view is undefined
ORIGINAL STACKTRACE:
require<.node_modules["@angular"].core.src.linker["element.js"]</AppElement</AppElement.prototype.detachView@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:56094:1
require<.node_modules["@angular"].core.src.linker["view_container_ref.js"]</ViewContainerRef_</ViewContainerRef_.prototype.remove@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:56294:20
require<.node_modules["@angular"].common.src.directives["ng_for.js"]</NgFor</NgFor.prototype._bulkRemove@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:70169:17
require<.node_modules["@angular"].common.src.directives["ng_for.js"]</NgFor</NgFor.prototype._applyChanges@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6[…] meteor.js:930:11
Exception in queued task: require<.node_modules["angular2-meteor"].dist["mongo_cursor_observer.js"]</MongoCursorObserver</MongoCursorObserver.prototype._removeAt@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:113587:9
require<.node_modules["angular2-meteor"].dist["mongo_cursor_observer.js"]</MongoCursorObserver</MongoCursorObserver.prototype._startCursorObserver/<.removedAt@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:113565:30
wrapInZone/</<@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:113280:13
require<.node_modules["zone.js"].dist["zone.js"]/</</Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:115233:20
require<.node_modules["zone.js"].dist["zone.js"]/</</Zone</Zone</Zone.prototype.run@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:115126:25
wrapInZone/<@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:113279:9
LocalCollection._observeFromObserveChanges/observeChangesCallbacks.removed@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3745:11
LocalCollection._CachingChangeObserver/self.applyChange.removed@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:3674:26
wrapInZone/</<@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:113280:13
require<.node_modules["zone.js"].dist["zone.js"]/</</Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:115233:20
require<.node_modules["zone.js"].dist["zone.js"]/</</Zone</Zone</Zone.prototype.run@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:115126:25
wrapInZone/<@http://localhost:3000/packages/modules.js?hash=a872180b9f50ad9899c4ab69fd1c84d32bd8c3d6:113279:9
.observeChanges/wrapCallback/</<@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:410:11
.runTask@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:721:11
.flush@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:749:5
.drain@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:757:7
LocalCollection.prototype.resumeObservers@http://localhost:3000/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:1149:3
endUpdate@http://localhost:3000/packages/mongo.js?hash=f257f65490c0d34a164a6d8801ede96905340462:271:11
.registerStore/</store[method]@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3613:27
._performWrites/<@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4457:43
_.forEach@http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:157:13
._performWrites@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4457:7
._flushBufferedWrites@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4423:5
._livedata_data@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4391:7
._livedata_nosub@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4663:5
Connection/onMessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3383:7
._launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:2736:11
_.forEach@http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:149:7
._launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:2735:9
REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:175:9
SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:1160:5
SockJS.prototype._didMessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:1218:13
SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:1365:9
</i>

But when I use 1 page (pageSize > total party), order party working fine!
Someone can help?

**Comment by tna274** [comment]
Update: When I use Server Side Search, the same Exception is occurred

**Comment by helloncanella** [comment]
same

**Comment by nebiljabari** [comment]
I suggest you to watch here [#114](https://github.com/Urigo/meteor-angular2.0-socially/issues/114)

**Comment by stomybexy** [comment]
I had to wrap

``` ts
this.parties = Parties.find({}, { sort: { name: this.nameOrder.get() } }); 
```

inside a zone.run to make it work. My final code looks like this:

``` ts
...
constructor(zone: NgZone) {
        super();
        this.zone = zone;
        this.autorun(() => {
            let options = {
                limit: this.pageSize,
                skip: (this.curPage.get() - 1) * this.pageSize,
                sort: { name: this.nameOrder.get() }
            };
            this.subscribe("parties", options, () => {
                this.zone.run(() => {
                    this.parties = Parties.find({}, { sort: { name: this.nameOrder.get() } });
                });
            }, true);

        }, true);


        this.autorun(() => {
            this.partiesSize = Counts.get("numberOfParties");
        }, true);

    }
...
```

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you

**Comment by tna274** [comment]
Thanks you so much!
