### ISSUE TITLE
Object is undefined in template

### ISSUE THREAD

**Issue by lukaszkukawski** [Urigo/meteor-angular2.0-socially#13]
Hi,
I have a issue/question

In this class:
https://github.com/lukaszkukawski/projectManagement/blob/error-objectUndefined/client/projects/details/project-details.ts
when i try to get object by id(id is correctly) using finOne in line 23 the object is correctly but in 26 this object is undefind so in template i have object undefind too.
Why this object when is finished load from mongo not binding to object in template?

**Comment by barbatus** [comment]
Yes, this is an expected behavior: you first load data, then use in the component.
Common practice is to check if that object is not null in the template with the help of `ng-if` directive.
Second, your template seems to be broken.

**Comment by lukaszkukawski** [comment]
Thank you for your response. I thought the same meteor care if something is get already or not yet. 
Great job!

**Comment by barbatus** [comment]
not sure it's possible in Angular2 currently.
