### ISSUE TITLE
Bootstrapping, Root Component Cannot find './app.html'

### ISSUE THREAD

**Issue by etskelly** [Urigo/meteor-angular2.0-socially#130]
Using Meteor 1.4

When adding the root component angular file app.ts, inside this file it cannot import the app.html template in the same client folder. It is present.

```
import 'reflect-metadata';
import { Component } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';
import template from './app.html';

@Component({
  selector: 'app',
  template
})

class Socially { }

bootstrap(Socially);
```

> App running at: http://localhost:3000/
> client/app.ts (4, 22): Cannot find module './app.html'.

**Comment by nebiljabari** [comment]
It's not linked to Meteor 1.4 but TypeScript. This bug should disappear with TS 2.0
more info here : [328](https://github.com/Urigo/angular2-meteor/issues/328)

**Comment by kamilkisiela** [comment]
@etskelly More info here Urigo/meteor-static-templates#9

**Comment by etskelly** [comment]
Excellent, thank you!

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
