### ISSUE TITLE
Step 4: Old forms module

### ISSUE THREAD

**Issue by roberto-naharro** [Urigo/meteor-angular2.0-socially#131]
I have this warning in the console:

> *It looks like you're using the old forms module. This will be opt-in in the next RC, and
>       will eventually be removed in favor of the new forms module. For more information, see:
>       https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

Maybe it should be changed to the new forms module

**Comment by nebiljabari** [comment]
Yes, the new form API was edited beginning of july with rc4. 
Angular will keep maintaining the old one

If you want to use the new API :
1- install the package: `meteor npm i --save @angular/forms`
2- disable the old form and bootstrap the new one :

```
import { disableDeprecatedForms, provideForms } from '@angular/forms';

bootstrap( AppComponent, [
  disableDeprecatedForms,
  provideForms
])
  .catch((error: any) => console.error(error));
```

3- import in your file component the package : `import { NgForm } from '@angular/forms';`
4- follow the new syntax on the google doc link

**Comment by roberto-naharro** [comment]
I have done all the changes but I'm not able to make it work

**Comment by nebiljabari** [comment]
Just to be clear _(I will assume you have correctly done the step 1 and 2 above)_ : 
- in your `parties-form.ts` you have `import { NgForm } from '@angular/forms';` ?
- in your `parties-form.html` you have respected the new syntax present in the google doc ?
- You have used (correctly) the trv (Template Reference Variable), the fancy: # in your directives ?
  Because the new API rely heavily on this

If yes to the 3 points, could you past your code from `parties-form.html` and `parties-form.ts`

**Comment by roberto-naharro** [comment]
After install the angular package I have read a lot of articles and I have done different changes, and everything it's working now. I'm going to put here all my files content if someone needs it:

`client/imports/parties-form/parties-form.ts` file:

```
import 'reflect-metadata';
import { Component } from '@angular/core';
import {
  FORM_DIRECTIVES,
  REACTIVE_FORM_DIRECTIVES,
  FormBuilder,
  FormGroup,
  FormControl,
  Validators
} from '@angular/forms';
import { Parties } from '../../../collections/parties.ts';

import template from './parties-form.html';

@Component({
  selector: 'parties-form',
  template,
  directives: [FORM_DIRECTIVES, REACTIVE_FORM_DIRECTIVES],
})
export class PartiesForm {
  partiesForm: FormGroup;

  constructor() {
    let fb = new FormBuilder();

    this.partiesForm = fb.group({
      name: ['', Validators.required],
      description: [''],
      location: ['', Validators.required]
    });
  }

  addParty(party) {
    if (this.partiesForm.valid) {
      Parties.insert({
        name: party.name,
        description: party.description,
        location: party.location
      });

      (<FormControl>this.partiesForm.controls['name']).updateValue('');
      (<FormControl>this.partiesForm.controls['description']).updateValue('');
      (<FormControl>this.partiesForm.controls['location']).updateValue('');
    }
  }
}
```

`client/imports/parties-form/parties-form.html` file:

```
<form [formGroup]="partiesForm" (submit)="addParty(partiesForm.value)">
  <label>Name</label>
  <input type="text" formControlName="name">
  <label>Description</label>
  <input type="text" formControlName="description">
  <label>Location</label>
  <input type="text" formControlName="location">
  <button>Add</button>
</form>
```

`client/app.ts` file:

```
import 'reflect-metadata';
import { Component, provide } from '@angular/core';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import { Parties }   from '../collections/parties';
import { Mongo }     from 'meteor/mongo';
import { PartiesForm } from './imports/parties-form/parties-form';
import { disableDeprecatedForms, provideForms } from '@angular/forms';

import template from './app.html';

@Component({
  selector: 'app',
  template,
  directives: [PartiesForm]
})
 class Socially {
    parties: Mongo.Cursor<Object>;

   constructor () {
     this.parties = Parties.find();
   }
 }

bootstrap(Socially, [
  disableDeprecatedForms(),
  provideForms(),
])
  .catch((error: any) => console.error(error));
```

This new form affects to step 6 also. You have to be careful

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
