### ISSUE TITLE
Step 18 password recovery email

### ISSUE THREAD

**Issue by jalalat** [Urigo/meteor-angular2.0-socially#138]
Password recovery functionality is not working. Can someone please provide me guidance on how to send a password recovery email to a user.

**Comment by dotansimha** [comment]
Hi @jalalat ,
Meteor's `email` package is in charge of sending those emails, and in development it's just printed to Meteor's log. If you wish to use the actual emails feature, you need to defined you email configuration for Meteor. 

Please follow the instructions here:
https://docs.meteor.com/api/email.html

**Comment by Urigo** [comment]
@dotansimha maybe it's a good idea to add a line about it in the tutorial?
