### ISSUE TITLE
Divergence between the code and the tutorial

### ISSUE THREAD

**Issue by fidelis** [Urigo/meteor-angular2.0-socially#139]
In the tutorial it says to save the file in "Add a file both/collections/**parties**/parties.collection.ts:" But every import points to **both/collections/parties.collection.ts** !!! Someone please correct the tutorial http://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding

**Comment by Urigo** [comment]
@fidelis thanks for noticing.
The way to do it is by the code examples as they are directly linked to the working repository.
Creating a PR to change the docs is very simple and is done by just clicking the "Improve this doc" button on the top right corner.
Would you care to submit a fix for this?

**Comment by fidelis** [comment]
Done!

**Comment by Urigo** [comment]
thanks
