### ISSUE TITLE
Cant import the login-buttons.scss

### ISSUE THREAD

**Issue by rajjejosefsson** [Urigo/meteor-angular2.0-socially#141]
Why can't I import the login-buttons.scss

main.scss inside client
`@import "{}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss";`

```
Errors prevented startup:

While processing files with angular2-compilers (for target web.browser):
/client/main.scss: Scss compiler error: File to import: {}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss not found in file: /Users/Rasmusjosefsson/Desktop/ng-meteor/socially/{}/client/main.scss

Your application has errors. Waiting for file change.
```

**Comment by saltcola** [comment]
I got same issue, how did you solve that??

**Comment by omt66** [comment]
Got the same exact error. Any feedback?

**Comment by freddiefish** [comment]
same problem here...

**Comment by amerzad** [comment]
@rajjejosefsson 
Same problem here!
What is the solution?

**Comment by aajajim** [comment]
I got the same issue, alll you need to do is to restart Meteor

**Comment by dotansimha** [comment]
It's an issue with Meteor, after adding the SCSS file with the import for the first time - Meteor unable to find the file - run Meteor again and it will solve your issue - I think that this issue was fixed in the latest RC of Meteor.

Please re-open if you still have any issues.

**Comment by tafelito** [comment]
I'm still having this issue, with latest Meteor release, 1.4.2

Restarting does not solve the issue, tried a few times, and I see the error every time

And what I see is that the file login-buttons.scss is missing inside node_modules/angular2-meteor-accounts-ui/build/

**Comment by tafelito** [comment]
Ok I finally was able to build, I had to use `angular2-meteor-accounts-ui@0.8.0` instead of the latest version `1.0.0`

**Comment by dotansimha** [comment]
@tafelito yeah we changed the accounts package in version 1.0.0, and now the CSS style is bundled inside the Component, and there is no need to import it manually. 
I will update the tutorial now. 

Thanks!

**Comment by tafelito** [comment]
Great, @dotansimha thank you!
