### ISSUE TITLE
Meteor Bootstrap is failing with latest angular2 version

### ISSUE THREAD

**Issue by mahesh-kedari** [Urigo/meteor-angular2.0-socially#142]
Below is the error log shown on browser console.

```
reflective_injector.js:786 Uncaught No provider for ApplicationRef!
ReflectiveInjector_._throwOrNull @ reflective_injector.js:786 
ReflectiveInjector_._getByKeyDefault @ reflective_injector.js:814 
ReflectiveInjector_._getByKey @ reflective_injector.js:777 
ReflectiveInjector_.get @ reflective_injector.js:586 
MeteorApp.bootstrap @ meteor_app.js:54 
bootstrap @ bootstrap.js:9 
runWeb @ main.ts:28 
meteorInstall.client.main.js @ main.ts:23
fileEvaluate @ install.js:153
require @ install.js:82
(anonymous function) @ parties.methods.ts:92
zone.js:101 GET http://localhost:3000/sockjs/info?cb=75ev0at2i1 
```

**Comment by mahesh-kedari** [comment]
This issue is coming from angular2-meteor-auto-bootstrap package. Callback for bootstrapModule() method is unable to locate ApplicationRef
`let appRef = moduleRef.injector.get(ApplicationRef);`
Is it updated in @angular/core package?

**Comment by Urigo** [comment]
Hi everyone and sorry for the late response.
We were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.3` and the latest Angular 2.0 and check out the new startup process on the updated Socially 2.0 tutorial.

Please open a new issue if it doesn't work for you
