### ISSUE TITLE
sorting parties by name - error when party name changes

### ISSUE THREAD

**Issue by mmwo** [Urigo/meteor-angular2.0-socially#143]
The entire collection of parties is sorted by name, but when the name of one party changes, which would effect with rearranging parties, the error from angular will show that the party is not defined.
`Cannot read property '_id' of undefined`
The error is available for example on the step 17 of the socially app which zip file I'm attaching here
[meteor-angular2.0-socially-step_17.zip](https://github.com/Urigo/meteor-angular2.0-socially/files/423364/meteor-angular2.0-socially-step_17.2.zip)

**Comment by dotansimha** [comment]
Hi @Jitra ,
This was already fixed in the current version of the tutorial.
Please reopen the issue if you still having problems. Thanks.
