### ISSUE TITLE
Tutorial dependencies are unclear

### ISSUE THREAD

**Issue by bobd-biz** [Urigo/meteor-angular2.0-socially#146]
The build/run dependencies for the tutorial are not clearly stated, particularly if you jump ahead to another step (like the end - step 22). It would be helpful to state the dependencies (meteor add/remove, etc.) for each step, especially if someone wants to download one of the zip files and start partway through the tutorial.

**Comment by Urigo** [comment]
Sorry for the late response.
We were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.3` and the latest Angular 2.0.

We've update the Socially 2.0 tutorial and the Blaze to Angular 2 migration tutorial for reference - https://www.angular-meteor.com/migration/angular2/intro

Sorry for the long wait, it was very hard to keep up with Angular 2 releases in latest months.

If you find issues, please open new ones on the Github repo.
