### ISSUE TITLE
Error: "client/app.component.html:1: Expected one of: <body>, <head>, <template>"

### ISSUE THREAD

**Issue by mikecoppola16** [Urigo/meteor-angular2.0-socially#147]
My meteor-angular2.0 project throws this error:

```
While processing files with templating (for target web.browser):
client/app.component.html:1: Expected one of: <body>, <head>, <template>
```

I have  meteor installed and I did run meteor npm install. Here are the contents of the files in my client folder:

**index.html:**

```
<head>
    <base href="/">
</head>

<body>
    <app>Loading...</app>
</body>
```

**main.ts**

```
import { bootstrap } from 'angular2-meteor-auto-bootstrap';

import { AppComponent } from './app.component';

bootstrap(AppComponent);
```

**app.component.ts**

```
import { Component } from '@angular/core';

import template from './app.component.html';

@Component({
  selector: 'app',
  template
})
export class AppComponent {}
```

**app.component.html**

`Hello World!`

**Comment by FaberNa** [comment]
wait node js is not required, meteor install all in one package. When you run the command 

`$ curl https://install.meteor.com/ | sh` or install on window with package is not required to install also nodeJs. 
Have you correctly download the template project ?

**Comment by mikecoppola16** [comment]
I'm not sure what you are asking in the first sentence? Yes I am working off the template project:
https://github.com/bsliran/angular2-meteor-base

**Comment by jerradpatch** [comment]
I am also getting this error after attempting to update a 2.0.0.rc4 project to 2.0.1 and then deleting the .meter, creating a new project in existing folder, and attempting to start the app.

**Comment by jerradpatch** [comment]
I just had to install the atmosphere packages from the link above

**Comment by haleo9000** [comment]
This might be too late, but are you building in the same directory as your meteor project? This could be what is responsible for this, as it's trying to compile html files which have already been compiled.

**Comment by ghost** [comment]
`meteor remove blaze-html-templates`
`meteor add angular2-compilers`
