### ISSUE TITLE
Tutorial not working in ios

### ISSUE THREAD

**Issue by idesignpixels** [Urigo/meteor-angular2.0-socially#149]
I have tried this at various stages of the tutorial but if you download at the start of step 17.
`meteor add-platform ios`
`meteor run ios-device`
It just shows a blank screen, it looks like the `<router-outlet>` is not displaying properly as when I add some html into app.component I see it appear but still no router outlet.
I see no errors in the xcode log.

It works on genymotion android simulator.

**Comment by idesignpixels** [comment]
It appears that theres an issue setting the initial root in the router on load as when I add this to my app.component constructor it will work.

```
setTimeout(() => {
    this.router.navigate(['/']);
}, 1);
```

But there must be a better solution to implement?

**Comment by Urigo** [comment]
does that still happens to you on the latest packages and the new updated tutorial?

**Comment by idesignpixels** [comment]
Hi @Urigo just tested, I am getting rendered content, it's just a single page with 3 cards, no interactions or navigation, is that right? (end of ionic step zip)

**Comment by dotansimha** [comment]
@Lindstrom1989 Can you please try again now? we made some changes and it works for me...

**Comment by dotansimha** [comment]
@Lindstrom1989 
Just verified it with the latest tutorial, XCode 7.3.1 installed, and running in iOS Simulator 9.3 (iPhone 6S), and everything looks good:
<img width="733" alt="screen shot 2016-10-18 at 13 26 45" src="https://cloud.githubusercontent.com/assets/3680083/19474013/85ecde64-9536-11e6-8448-31c84b459fca.png">

Please re-open the issue if you still having problems. Thanks.
