### ISSUE TITLE
URL does not change on "Cancel" from the party details route

### ISSUE THREAD

**Issue by horyd** [Urigo/meteor-angular2.0-socially#15]
I pulled down the zip from the beginning of step 8 to see if the problem I was experiencing on my own repository was fixed in yours but it doesn't look like it.

When you click "Cancel" from viewing a given party detail, the view successfully changes but the URL remains the same. When I had this as a anchor tag instead of a button the produced href was null, on hover the indicative URL of the anchor tag was "/party/null" as noted in the bottom left hand corner of Chrome.

Any help with this would be great :) Thanks guys!

**Comment by barbatus** [comment]
There was already a similar bug here. Its an Angular2 issue, will fixed in beta.00 https://github.com/mgechev/angular2-seed/issues/264
