### ISSUE TITLE
Step 20: Cannot find module 'meteor/jalik:ufs'

### ISSUE THREAD

**Issue by FaberNa** [Urigo/meteor-angular2.0-socially#152]
I've installed these two packages : 

![schermata 2016-09-12 alle 21 31 37](https://cloud.githubusercontent.com/assets/8997051/18449685/6d79ca3a-7930-11e6-8d34-f30c7d9fc749.png)

In my code and on console i see 

`cannot find module 'meteor/jalik:ufs'`

**Comment by FaberNa** [comment]
Just read the tutorial and follow the steps

**Comment by Leskevicius** [comment]
What type of suggestion is this?...

**Comment by Urigo** [comment]
@Leskevicius it means that we updated the tutorial and now it works :)

**Comment by ryanlion** [comment]
not really....it doesn't work

**Comment by jamalazza** [comment]
at now it doesn't work
