### ISSUE TITLE
Update tutorial

### ISSUE THREAD

**Issue by FaberNa** [Urigo/meteor-angular2.0-socially#153]
@Urigo 
Probably the best way to run tutorial is to use the exact version of package for dependencies.
In adding, why don't create a simple post or an adding place where to find Q&A about Meteor, one for me more interesting is this : https://forums.meteor.com/t/what-is-difference-between-meteor-npm-install-and-meteor-add/23676

**Comment by Urigo** [comment]
@FaberNa sorry for the late response but we were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.2_1` and the latest Angular 2.0.

We've update the Socially 2.0 tutorial and the Blaze to Angular 2 migration tutorial for reference - http://www.angular-meteor.com/migration/angular2/intro

Sorry for the long wait, it was very hard to keep up with Angular 2 releases in latest months.

About your question, I've answered inside

**Comment by FaberNa** [comment]
But now i've stable version.. I try with your response :) to add : 
- angular2-meteor@0.7.0
-  angular2-compilers@0.6.2_1 
  and latest Angular 2.0 
  Thanks very much @Urigo
