### ISSUE TITLE
Step 0, [ts] Cannot find module './app.component.html'.

### ISSUE THREAD

**Issue by daslicht** [Urigo/meteor-angular2.0-socially#156]
Hi, 
VS Code is showing me the following error, but the code is working : 

```
[ts] Cannot find module './app.component.html'.
```

Is there a way to fix this issue ?

**Comment by FaberNa** [comment]
can you  paste your tsconfig.json here ??

**Comment by daslicht** [comment]
I solved it meanwhile , but I have no clue why the error disappeared, have nothing changed starnge.
Thank you very much !

**Comment by daslicht** [comment]
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "isolatedModules": false,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by Neftedollar** [comment]
I've got the same problem!
@daslicht let's kargo!) What did you do?

**Comment by daslicht** [comment]
I have no clue :) It just worked , really strange

**Comment by PandaCoffeeBara** [comment]
So I have the same problem and there is no resolution yet ?

**Comment by PandaCoffeeBara** [comment]
I had to import into my app.component.ts

 import 'zone.js';
import 'reflect-metadata'; 

and it worked
