### ISSUE TITLE
Pagination throwing Error:  TypeError: core_1.NgModule is not a function

### ISSUE THREAD

**Issue by mikecoppola16** [Urigo/meteor-angular2.0-socially#158]
I'm at the point where I'm implementing paging but its throwing an error. The console throws an error in parties-list.component.ts on line 7. The code at line 7 is:

`import { PaginationService, PaginationControlsCmp } from 'ng2-pagination';`
The FULL error thrown is:

 ng2-pagination.js:26Uncaught TypeError: core_1.NgModule is not a function

I'm thinking maybe the ng2-pagination is not compatible with my version of angular I'm running inside of meteor but not sure how to find out or what Angular packages to update?

```
{
  "name": "angular2-meteor-base",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs"
  },
  "devDependencies": {
    "chai": "3.5.0",
    "chai-spies": "0.7.1"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-alpha.8",
    "angular2-meteor": "0.6.2",
    "angular2-meteor-accounts-ui": "^0.6.1",
    "angular2-meteor-auto-bootstrap": "0.6.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "0.2.3",
    "ng2-pagination": "https://registry.npmjs.org/ng2-pagination/-/ng2-pagination-0.4.1.tgz",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  }
}
```

My version of meteor is: 1.4.1.1

**Comment by oberoivarun** [comment]
+1 Same issue here!

**Comment by Urigo** [comment]
Hi everyone and sorry for the late response.
We were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.3` and the latest Angular 2.0.

We've update the Socially 2.0 tutorial and the Blaze to Angular 2 migration tutorial for reference - https://www.angular-meteor.com/migration/angular2/intro

Sorry for the long wait, it was very hard to keep up with Angular 2 releases in latest months.

If you find issues, please open new ones on the Github repo.
