### ISSUE TITLE
Step 18 - angular-material

### ISSUE THREAD

**Issue by FaberNa** [Urigo/meteor-angular2.0-socially#159]
In angular material step there isn't a button for filter on location, i recover it from past step and it works ( but it's not in the same style, it's not material ) 
`
<md-input #searchtext placeholder="Search by Location"></md-input>
  <button type="button" (click)="search(searchtext.value)">Search</button>
`

Alson in add when i filter for one location the filter work but when i try to filter another time it doesn't work, the query is building correct but the set of json seem unvariant ...

**Comment by dotansimha** [comment]
That's right. Oops.
Fixed in https://github.com/Urigo/meteor-angular2.0-socially/commit/6ed4f72ff7d1988001ed3cb82b699e1d0cbe18a4#diff-4a06f186122e226621844b23c32aede7R16
Thanks @FaberNa
