### ISSUE TITLE
templateUrl - external html does not update

### ISSUE THREAD

**Issue by Guro** [Urigo/meteor-angular2.0-socially#16]
Hi i'm following angular-meteor tutorial on official site but have encountered strange problem:
i have some component which has templateUrl: 'client/boards-form/form.html'
changing form.html template does not take effect, if i would change path to a different file i.e form2.html
it will render new template once but afterwards no changes that was made to the file will be reflected on actual app.

Additional info: just downloaded source of:
meteor-angular2.0-socially-step_04
same problem occurs.

as i'm seeing that happens only for external HTML specified by templateUrl, if i change to template:'<b>inline template </b>' then everything works perfectly

Can someone suggest what could cause it? tried meteor reset but it does't help
Thanks

**Comment by barbatus** [comment]
Yes, that's because this template is being cached. There seems to be no way currently to control caching  in the `@View` annotation. But you can always do it (i.e., turn off caching for a particular site) today in most browsers with the help of development tools.

**Comment by justworxs** [comment]
I don't believe that the browser cache is the problem, I cleared the cache for the my default test browser (safari) and that didn't seem to work. 

I also tried another browser (firefox) which I have never browsed to http://localhost:3000 before with and the server returned the old data.

I feel the issues is in the meteor server.

Is there a mechanism whereby I can clear the meteor server

Thanks

**Comment by barbatus** [comment]
Considered resolved due to no feedback.
