### ISSUE TITLE
meteor-rxjs version in package.json

### ISSUE THREAD

**Issue by elpddev** [Urigo/meteor-angular2.0-socially#162]
Hi, I have created the base project and running npm install. I get an error

`No compatible version found: meteor-rxjs@0.3.0`

Looking at the [meteor-rxjs npm site](https://www.npmjs.com/package/meteor-rxjs) its says the latest version published is 0.2.3. 

After changing that in the package.json, npm install as ended successfully.

**Comment by Urigo** [comment]
published now, sorry for the delay
