### ISSUE TITLE
Tutorial fails to configure on Windows 10

### ISSUE THREAD

**Issue by bobd-biz** [Urigo/meteor-angular2.0-socially#165]
Cloned from git, and then tried "meteor npm install". Had to ^C after several minutes.

c:\Build\meteor>git clone https://github.com/Urigo/meteor-angular2.0-socially.git
Cloning into 'meteor-angular2.0-socially'...
remote: Counting objects: 2742, done.
remote: Compressing objects: 100% (945/945), done.
remote: Total 2742 (delta 513), reused 0 (delta 0), pack-reused 1664R
Receiving objects: 100% (2742/2742), 270.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1316/1316), done.
Checking connectivity... done.

c:\Build\meteor>cd meteor-angular2.0-socially

c:\Build\meteor\meteor-angular2.0-socially>meteor npm install
npm ERR! git submodule -q update --init --recursive: C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 18: .: git-sh-setup: file not found
npm ERR! git submodule -q update --init --recursive:
npm ERR! git clone --template=C:\Users\Bob\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/dotansimha/angular2-file-drop.git C:\Users\Bob\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-dotansimha-angular2-file-drop-git-a3569f1abdb6c61739d93456758479901bc41557-a3a3c85f: Cloning into bare repository 'C:\Users\Bob\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-dotansimha-angular2-file-drop-git-a3569f1abdb6c61739d93456758479901bc41557-a3a3c85f'...
npm ERR! git clone --template=C:\Users\Bob\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/dotansimha/angular2-file-drop.git C:\Users\Bob\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-dotansimha-angular2-file-drop-git-a3569f1abdb6c61739d93456758479901bc41557-a3a3c85f: fatal: Unable to find remote helper for 'https'
^CTerminate batch job (Y/N)?
^C
c:\Build\meteor\meteor-angular2.0-socially>

**Comment by dotansimha** [comment]
Fixed. Thanks @rwdietrich. 
That caused by a NPM module that installed using Git url. changed it now to the actual version of the package.
