### ISSUE TITLE
Errors in full socially tutorial

### ISSUE THREAD

**Issue by bobd-biz** [Urigo/meteor-angular2.0-socially#166]
Cloned the full tutorial from git on a Linux machine, did "meteor npm install" followed by "meteor", and got the following errors:

$ meteor
[[[[[ ~/build/meteor/meteor-angular2.0-socially ]]]]]

=> Started proxy.
=> Started MongoDB.
client/imports/app/auth/login.component.mobile.ts (33, 16): Property 'requestPhoneVerification' does not exist on type 'typeof Accounts'.
client/imports/app/auth/login.component.mobile.ts (50, 16): Property 'verifyPhone' does not exist on type 'typeof Accounts'.

Unable to resolve some modules:

  "try-thread-sleep" in /home/bobd/build/meteor/meteor-angular2.0-socially/node_modules/spawn-sync/lib/spawn-sync.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save try-thread-sleep

Unable to resolve some modules:

  "try-thread-sleep" in /home/bobd/build/meteor/meteor-angular2.0-socially/node_modules/spawn-sync/lib/spawn-sync.js (os.linux.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save try-thread-sleep

W20161009-16:37:22.529(-7)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20161009-16:37:24.393(-7)? (STDERR) While this implementation will work correctly, it is known to be
W20161009-16:37:24.395(-7)? (STDERR) approximately three times slower than the native implementation.
W20161009-16:37:24.396(-7)? (STDERR) In order to use the native implementation instead, run
W20161009-16:37:24.397(-7)? (STDERR)
W20161009-16:37:24.398(-7)? (STDERR)   meteor npm install --save bcrypt
W20161009-16:37:24.398(-7)? (STDERR)
W20161009-16:37:24.400(-7)? (STDERR) in the root directory of your application.

**Comment by SheshoVega** [comment]
same error in Ubuntu 16.04

**Comment by dotansimha** [comment]
Yeah that caused because of using `gm` package, and `try-thread-sleep` is a dependency of this package. Meteor uses the latest version of Node in it's latest versions, and now the peer dependencies no longer installed automatically. 

I updated the tutorial and added it.

Thanks.
