### ISSUE TITLE
Step 4.2 Tutorial import path

### ISSUE THREAD

**Issue by Eraldo** [Urigo/meteor-angular2.0-socially#167]
I ran into an error trying to stick to the tutorial:

In this part of the tutorial: http://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding
there is a code snipped included (step 4.2) showing the line `import { Parties } from '../../both/collections/parties.collection';`.
That got me an error. Looking at it I figured the file to be edited is at `client/imports/app/` so going two directories above (`../../`) would get me to `client`.
Since in the import line I read `both` I guessed it could be missing one hop up.
So I changed it to `import { Parties } from '../../../both/collections/parties.collection';` and then it worked again.

Can anyone confirm this? Did I structure something wrong?

Reference code snippet that was included:
https://github.com/Urigo/meteor-angular2.0-socially/blob/master/steps/step4.md#step-42-import-parties-collection

**Comment by DAB0mB** [comment]
Fixed and deployed. See https://github.com/Urigo/meteor-angular2.0-socially/blob/master/steps/step4.md

**Comment by Eraldo** [comment]
Thanks. :)
