### ISSUE TITLE
Error on Meteor start

### ISSUE THREAD

**Issue by GrmpyPmpkin** [Urigo/meteor-angular2.0-socially#171]
I am new to meteor.
Following the instruction in the tutorial. I have installed meteor, created the package and installed the npm packages. All which went through fine. However now when I am going to run the app I am getting an error. Hope someone can point out what I have done wrong. Thanks

```
$ meteor
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with angular2-compilers (for target web.browser):

   C:\tools\isobuild\compiler-plugin.js:698:15: 'data' option to addAsset must be a Buffer or String.
   at ResourceSlot.addAsset (C:\tools\isobuild\compiler-plugin.js:698:15)
   at InputFile.addAsset (C:\tools\isobuild\compiler-plugin.js:463:24)
   at SassCompilerExtended.addCompileResult (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
   at packages/caching-compiler/multi-file-caching-compiler.js:144:14
   at packages/caching-compiler/multi-file-caching-compiler.js:97:11
   at C:\Users\Danielle\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\Danielle\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\Danielle\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\Danielle\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
   at SassCompilerExtended.processFilesForTarget (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
   at _loop (packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
   at StyleCompiler.processFilesForTarget (packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)

=> Your application has errors. Waiting for file change.
```

**Comment by dotansimha** [comment]
Hi @danielleburgess ,

Did you clone the tutorial repository or did you start it from scratch? And in which step are you?

Which version of Meteor you are running globally? (run `meteor --version`), and which NPM version do you have (run `npm --version`), Also, did you installed the dependencies using `npm install` or `meteor npm install`? 
Also, please provide your `.meteor/releases`, `.meteor/packages` and `.meteor/versions` file so I can get a better understanding on which packages versions you have.

Also, it would be great if you could provide the actual repository so I can see the actual code.

Thanks.

**Comment by GrmpyPmpkin** [comment]
Hi,

I installed meteor using the windows installer - version Meteor 1.4.1.2. 
When I did that, I meteor `meteor create --example angular2-boilerplate socially` just like it states in the tutorial, running this told me to do it by git cloning the repo.:
![image](https://cloud.githubusercontent.com/assets/4669195/19478209/873736a4-9539-11e6-8a18-08f87a257688.png)

After it cloned I went into the socially folder and ran `meteor npm install`. NPM version 3.10.5.

Then again like it states I tried to run the meteor - which gave me my error.

I haven't even begun adding any different code into the package, but I have supplied the files you stated.

`.meteor/packages`

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12_1                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0_1   # CSS minifier run for production mode
standard-minifier-js@1.2.0_1    # JS minifier run for production mode
es5-shim@4.6.14_1                # ECMAScript 5 compatibility for older browsers.

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
angular2-compilers
practicalmeteor:mocha
xolvio:cleaner
hwillson:stub-collections
dispatch:mocha-phantomjs
shell-server@0.2.1
```

`.meteor/versions`

```
allow-deny@1.0.5
angular2-compilers@0.6.3
autopublish@1.0.7
autoupdate@1.2.11
babel-compiler@6.9.1_1
babel-runtime@0.1.11_1
barbatus:css-compiler@0.3.3
barbatus:scss-compiler@3.8.2
barbatus:typescript@0.4.1
barbatus:typescript-compiler@0.7.1_1
barbatus:typescript-runtime@0.1.2
base64@1.0.9
binary-heap@1.0.9
blaze@2.1.9
blaze-tools@1.0.10
boilerplate-generator@1.0.10
caching-compiler@1.0.6
caching-html-compiler@1.0.6
callback-hook@1.0.9
check@1.2.3
coffeescript@1.1.4
ddp@1.2.5
ddp-client@1.2.9
ddp-common@1.2.6
ddp-server@1.2.10
deps@1.0.12
diff-sequence@1.0.6
dispatch:mocha-phantomjs@0.1.7
dispatch:phantomjs-tests@0.0.5
ecmascript@0.5.8_1
ecmascript-runtime@0.3.14_1
ejson@1.0.12
es5-shim@4.6.14_1
fastclick@1.0.12
geojson-utils@1.0.9
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.1.8
hwillson:stub-collections@1.0.1
id-map@1.0.8
insecure@1.0.7
jquery@1.11.9
launch-screen@1.0.12
livedata@1.0.18
logging@1.1.15_1
meteor@1.2.17_1
meteor-base@1.0.4
minifier-css@1.2.14_1
minifier-js@1.2.14_1
minimongo@1.0.17
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.7.6_1
modules-runtime@0.7.6_1
mongo@1.1.12_1
mongo-id@1.0.5
npm-mongo@1.5.49
observe-sequence@1.0.12
ordered-dict@1.0.8
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.8.7
random@1.0.10
reactive-var@1.0.10
reload@1.1.10
retry@1.0.8
routepolicy@1.0.11
shell-server@0.2.1
spacebars@1.0.13
spacebars-compiler@1.0.13
standard-minifier-css@1.2.0_1
standard-minifier-js@1.2.0_1
templating@1.1.14
templating-tools@1.0.5
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.0
ui@1.0.12
underscore@1.0.9
urigo:static-html-compiler@0.1.8
url@1.0.10
webapp@1.3.11_1
webapp-hashing@1.0.9
xolvio:cleaner@0.3.1
```

I don't see a .meteor/releases file, but I have the .meteor/release.

`.meteor/release`
`METEOR@1.4.1.2`

**Comment by dotansimha** [comment]
@danielleburgess It looks like that error comes from `angular2-compilers` package, I will check it out in my local env. Did you add any file? or just cloned it? 
Also, I recommend to update your NPM to the latest version, and not using version 3 since it does not match Meteor / Angular2-Meteor requirements and might cause a lot of issues.

**Comment by dotansimha** [comment]
It works great for me with those versions on Mac. 
@barbatus any idea?

**Comment by GrmpyPmpkin** [comment]
It seems to be a Windows problem with angular2-compilers. I had to set it to be `angular2-compilers@=0.6.0`.  To get the meteor to actually start. But now in the browser I have another error.

![image](https://cloud.githubusercontent.com/assets/4669195/19481103/be9872c4-9544-11e6-994d-aa90a271431b.png)

Any ideas?

**Comment by dotansimha** [comment]
Yeah that makes sense, because the boilerplate needs the latest version. 
You can make it work now by changing the definitions of the `Component`s, you need to change the styles imports to be like that:

``` js
@Component({
 /// ...
  styles: [ style.innerText ]
 // ...
})
```

And I almost sure that you need to change the import of the `style` to be `import * as style from ..`.

**Comment by GrmpyPmpkin** [comment]
Just tried updating the `angular2-compilers@=0.6.2_1` instead or 6.0. This seems to work perfectly, and I then don't need to change any of the style imports :). 

Thanks for all your help.

**Comment by dotansimha** [comment]
@danielleburgess you are welcome! I still recommend you to track the newer versions of the compilers package.
