### ISSUE TITLE
accounts-ui

### ISSUE THREAD

**Issue by tafelito** [Urigo/meteor-angular2.0-socially#175]
Hi guys, I was following the tutorial and I see that in step 16.2 you mentioned the package `barbatus:ng2-meteor-accounts-ui` but you don't actually use it anywhere, so I was wondering what was the difference between that one and `angular2-meteor-accounts-ui`, if there is one, or if its just an old package and the documentation is not updated.
Thanks

**Comment by dotansimha** [comment]
Hi @tafelito, where exactly did you see the `barbatus:ng2-meteor-accounts-ui` package? I didn't find any mention of it...

**Comment by tafelito** [comment]
It's right after the 16.2 step. It says 

> Now run the app. Make sure you have added barbatus:ng2-meteor-accounts for it to work.

**Comment by dotansimha** [comment]
Yeah just found it. 
Fixed and will deploy soon.

Thanks @tafelito !
