### ISSUE TITLE
Undefined variable: "$color3

### ISSUE THREAD

**Issue by tafelito** [Urigo/meteor-angular2.0-socially#176]
Hi, I think the step 17 of the tutorial is not working anymore. I'm having this error when I try to compile `/client/imports/app/parties/parties-list.component.scss: Scss compiler error: Undefined variable: "$color3".` and I checked the version for the repo and it also has the same issue. Could that be anything related to the latest package updates?

**Comment by dotansimha** [comment]
Yeah that happened because I updated the usage of styles file, and didn't add the colors in a separate file with an import. 
I updated the commits and the tutorial text, we will soon deploy it to the live website.

Thanks @tafelito.

**Comment by tafelito** [comment]
It's right after the 16.2 step. It says 

> Now run the app. Make sure you have added barbatus:ng2-meteor-accounts for it to work.

**Comment by tafelito** [comment]
Ok great, thank you! I'm very new to angular, so every error I see, I'm not always capable of solving it. So in the meantime, what'd be the best solution here , add the `main.scss` to the ts components as an extra style, or import it into the components scss?

**Comment by dotansimha** [comment]
The `main.scss` styles file should contain only out-of-angular-scope style, like `html`, `body`, and contain styles that you want to reuse and apply multiple times, for example: `pull-right` (example from Bootstrap). 

The `styles` and `styleUrls` should contain only styles that apply to the specific Component, and you won't be able to use them outside the Component.

I wrote an answer recently that might help you understand the Angular 2 styles encapsulation:
https://github.com/Urigo/angular2-meteor/issues/429#issuecomment-257168571

**Comment by tafelito** [comment]
Ok so If I understand that correct, why the example is complaining about the $color3 that is present in the `client/main.scss`? Shouldn't the styles from the component, like `party-details.component.scss`have access to whatever values you put in the `main.scss`?

**Comment by dotansimha** [comment]
The problem is with `/client/imports/app/parties/parties-list.component.scss` which are the styles for the`PartiesListComponent` only. but in this file we expect to have `$color3` which is a SCSS variable the defined the global colors of the app. 
Each file that uses `$color3` must use SASS's `@import` to load the global file `colors.scss` which defines the actual colors...

**Comment by tafelito** [comment]
Ok got it now. Thanks again for the quick response and the explanation. I think I can keep going now now 😜
