### ISSUE TITLE
PrimeNG integration

### ISSUE THREAD

**Issue by hakikihacioglu** [Urigo/meteor-angular2.0-socially#182]
Hi,

How can I integrate PrimeNG in my meteor-angular app. On http://www.primefaces.org/primeng/#/setup there is a setup example with webpack.config.js and  systemjs.config.js. I followed the whole socially tutorial for angular 2 but didn't see any usage of those files. 

Thanks for the help

**Comment by kamilkisiela** [comment]
Think about the Meteor build tool as a it would be the webpack. As you can see, there's pretty much nothing to do in terms PrimeNG and Webpack. 

Try to simply import those css files of PrimeNG into your project and that's it :)

If you have any question or you encountered some trouble, just @mention me, I will try to help you :)

**Comment by Urigo** [comment]
@hakikihacioglu please just try and if it's not working for you open an issue with a reproduction.
thanks!
