### ISSUE TITLE
Why a React favicon in a Meteor / Angular 2 project ?

### ISSUE THREAD

**Issue by kenp77** [Urigo/meteor-angular2.0-socially#186]
Why i'm having a React favicon when i run the application ? it's kind of strange and confusing ! That mean we shoud react instead ? lol

**Comment by Urigo** [comment]
where do you see the React fav.icon?

**Comment by vamsivarikuti** [comment]
@Urigo 
new [create-react-app](https://github.com/facebookincubator/create-react-app) tool runs react on port 3000 and meteor also runs on same port, chrome is displaying react favicon.

I don't think this is an issue.

**Comment by Urigo** [comment]
thanks
