### ISSUE TITLE
Missing folder and files

### ISSUE THREAD

**Issue by ascensus-mdb** [Urigo/meteor-angular2.0-socially#19]
1. Trying to check any of the file on github I am redirected to 404 page. The file doesn't exist.

http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure
1. Int the repository there is no folder 'typings"  and file party.d.ts

After proceed to step 8 my terminal gives a bunch of errors related to types.

**Comment by barbatus** [comment]
Party.d.ts is a file that you create yourself, as clearly (hopefully) stated in the this step ("folder structure"), but "typings" folder should be there. Do you say that "typings" folder is missing at this point?
