### ISSUE TITLE
Step 6.11: no diff

### ISSUE THREAD

**Issue by jplambert** [Urigo/meteor-angular2.0-socially#192]
Everything is in the title.

Please see the screen capture:
![capture](https://cloud.githubusercontent.com/assets/10744293/21093263/2772f74c-c051-11e6-9628-ace8b1481e68.PNG)

**Comment by DAB0mB** [comment]
@jplambert The issue is fixed :-) https://github.com/Urigo/meteor-angular2.0-socially/blob/master/manuals/views/step6.md
