### ISSUE TITLE
Add chapter on angular-material2

### ISSUE THREAD

**Issue by sireskay** [Urigo/meteor-angular2.0-socially#2]
Good morning @Urigo, and thank for sharing this! I am wondering if you have been successful with implementing ng-material with angular2.0?

**Comment by Splaktar** [comment]
@skolade Angular Material does not currently support Angular 2. 

There is an [issue](https://github.com/angular/material/issues/6336) to allow it to support ngUpgrade but there is no ETA for that work to be done.

Work on Angular Material 2 is happening [here](https://github.com/angular/material2).

Discussion on these topics would likely be better done there or on the Angular Material [forums](https://groups.google.com/forum/#!forum/ngmaterial).

**Comment by TrikinCurt** [comment]
And from a guy who REGRETS using angular-material, just use bootstrap :)  Bootstrap4 gives you flexbox, copying the design elements - there are bootstrap libraries to help.  I went through the millions of bugs using AM, to now having it prevent us from upgrading to ng2.  Hard to say that is worth it!

there IS a bootstrap4 ng2 component from the angular-ui team.

**Comment by Urigo** [comment]
If someone is trying, try to use the Angular2-Meteor 0.5.0-beta and bring [material2](https://github.com/angular/material2) from Npm

**Comment by dotansimha** [comment]
With the new Meteor 1.3 tutorial we have this chapter!! With the latest beta of Ng2-Material package from NPM !!

**Comment by dohomi** [comment]
Hi guys,
I tried to follow the socially package as a reference and bootstrapped a small app. But I don't get `@angular2-material` running:
`Failed to parse SourceMap: http://localhost:3000/usr/local/google/home/jelbourn/material2/tmp/broccoli…_compiler-input_base_path-IydvmmBU.tmp/0/components/toolbar/toolbar.js.map`
Does anyone have seen this error as well? I tried even the `ng2-material`with the same error.
Thanks Dominic

**Comment by lorenzogm** [comment]
@dohomi Hi!

I got the same error, did you fixed it?

Thanks!

**Comment by dohomi** [comment]
Hi @lorenzogm I think because in the tutorial they use ng2-material in a different version of angular-material2 (alpha-4 instead of alpha-5). It might just help do downgrade that version but I haven't tried. Material is still in very early stage and if you check out their issues the compiler problem is reported and not yet fixed.
