### ISSUE TITLE
search in Chpater 9 in parties-form.ts doesn't work when search yields no results

### ISSUE THREAD

**Issue by ylcoder** [Urigo/meteor-angular2.0-socially#22]
the screen fails to refresh - should be empty list of parties when search yields no results.  if we do a matching search next time, the new results are added to the old one.

Sorry I couldn't fins any issue with the code though.

**Comment by barbatus** [comment]
yes, these was an issue with that, please check out with latest package version.

**Comment by ylcoder** [comment]
Thanks a lot Alex for getting back to me.  Looks like we need to implement the search on subscribe/publish queries.  is it what it is?  

```
  From: Alex <notifications@github.com>
```

 To: Urigo/meteor-angular2.0-socially meteor-angular2.0-socially@noreply.github.com 
Cc: ylcoder lyaolong@yahoo.com
 Sent: Saturday, December 26, 2015 3:03 AM
 Subject: Re: [meteor-angular2.0-socially] search in Chpater 9 in parties-form.ts doesn't work when search yields no results (#22)

yes, these was an issue with that, please check out with latest package version.—

**Comment by barbatus** [comment]
@ylcoder yes, it unfolds gradually with the search subscribe/publish in 12th step or so.
