### ISSUE TITLE
Compiler error after "meteor add tmeasday:publish-counts"

### ISSUE THREAD

**Issue by ylcoder** [Urigo/meteor-angular2.0-socially#23]
In chapter 12 for Angular 2, after "meteor add tmeasday:publish-counts", there is no type definition generated for the package and got the following error:

=> Started proxy.
=> Started MongoDB.
server/parties.ts (26, 5): Cannot find name 'Counts'.
=> Started your app.
//server/parties.ts
Meteor.publish('parties', function(options) {
    Counts.publish(this, 'numberOfParties', Parties.find(buildQuery.call(this)), { noReady: true });
    return Parties.find(buildQuery.call(this), options);
});

Is there anything additional I need to do to add the type definitions for the new package?  It seemed work for other packages. Should that be automatic when add meteor packages?

Thanks.

**Comment by barbatus** [comment]
As you understand, it's a regular random meteor package, and even not a NPM.
So, definition files are not available and likely won't be. Unless somebody either will create that files himself and upload them onto http://definitelytyped.org or try to pursue the package author to do that (which is unlikely).

**Comment by ylcoder** [comment]
Ok thanks. 

YL

**Comment by Lavan** [comment]
I made myself this definition:

``` typescript
declare module Counts {

    interface Options {
        noReady?:boolean;
        nonReactive?: boolean;
        countFromField?: string;
        countFromFieldLength?:string;
        noWarnings?: boolean;
    }

    function publish(subscription:Object, counterName:string, cursor:Mongo.Cursor, options?:Options);

    function get(counterName:string):number;

    function has(counterName:string):boolean;

    function noWarnings();
}
```

Which seems to work nicely, but as I'm a complete noob when it comes to typedefinitions I haven't uploaded it anywhere. I thought someone might have use for it though.

**Comment by barbatus** [comment]
@Lavan Nice. If I have time I'll contribute it to http://definitelytyped.org/guides/contributing.html. You could try it too, it's not hard.

**Comment by ShMcK** [comment]
There is an existing [`publish-counts.d.ts`](https://github.com/correpw/meteor-publish-counts.d.ts/blob/master/Counts.d.ts) file, though it has yet to be published to definitely-typed. 

I've proposed a [link](https://github.com/ShMcK/angular-meteor/commit/9ceb9b894b7e612b54b4bcd98789d525dec0f8f9) to the definition in the tutorial and a [request for it to get published](https://github.com/correpw/meteor-publish-counts.d.ts/issues/1).

**Comment by Neftedollar** [comment]
Hi all, I'm the owner of [this file](https://github.com/correpw/meteor-publish-counts.d.ts/blob/master/Counts.d.ts), but I have no time to learn typings services, so If you need the file you can add ith anywhere you want.Thanks.
