### ISSUE TITLE
Cannot find name 'Counts'

### ISSUE THREAD

**Issue by wbartussek** [Urigo/meteor-angular2.0-socially#25]
meteor
[[[[[ ~/Apps/meteor-angular2.0-socially-master ]]]]]

=> Started proxy.  
=> Started MongoDB.  
client/parties-list/parties-list.ts (59, 32): Cannot find name 'Counts'.
server/parties.ts (34, 5): Cannot find name 'Counts'.
=> Started your app.                          

=> App running at: http://localhost:3000/

**Comment by wbartussek** [comment]
Although the intended purpose of 'Counts' is clear I can't figure out where it is taken from and how to correct the error. I'm just working through the tutorial and am new to this.

**Comment by barbatus** [comment]
duplicated https://github.com/Urigo/meteor-angular2.0-socially/issues/23
