### ISSUE TITLE
step 7.2 and 7.3 missing <Party> in tutorial

### ISSUE THREAD

**Issue by deltaag** [Urigo/meteor-angular2.0-socially#27]
Thanks Urigo for this awesome tutorial.

Line 4 of the code in step 7.2 is showing:
`export var Parties = new Mongo.Collection('parties');`
I think it should be:
`export var Parties = new Mongo.Collection<Party>('parties');`

This causes step 7.3 and 7.4 not to work.

Line 21 of step 7.3 is:
`parties: Mongo.Cursor;`
I think it should be:
`parties: Mongo.Cursor<Party>;`

Cheers.

**Comment by Urigo** [comment]
Deployed, please check if it fixes the problem
