### ISSUE TITLE
Typings folder not created

### ISSUE THREAD

**Issue by byGui** [Urigo/meteor-angular2.0-socially#28]
I'm following the tutorial and running `meteor` doesn't create any typings folder. I've tried several times creating the project again but it's not there.

Is the tutorial outdated or the folder should be there and something is running wrong?

**Comment by barbatus** [comment]
Yes, there was an issue with that, but fixed in the last version. Run pls meteor update and then check out.

**Comment by byGui** [comment]
Thanks, It's working now
