### ISSUE TITLE
Require error

### ISSUE THREAD

**Issue by niallobrien** [Urigo/meteor-angular2.0-socially#3]
There's an error related to `require` in the browser console upon clone & run.

**Comment by firebait** [comment]
I'm having that same issue while creating a new application using the following packages:

meteor-platform
autopublish
insecure
angular:angular2
netanelgilad:angular2-typescript

**Comment by firebait** [comment]
This PR solves that issue. https://github.com/netanelgilad/meteor-angular2-typescript/pull/3
You can clone the project to your packages directory and modify it if you want to test it out.

**Comment by epotvin** [comment]
Hi guys, 

For me it didn't resolve the issue. 

Running  "sudo npm update typescript" did.

Emmanuel

**Comment by Urigo** [comment]
Using the new Typescript package should fix that.
Please let me know if it didn't (update from the tutorial)
