### ISSUE TITLE
'Cannot find module' for SystemJS modules in Atom

### ISSUE THREAD

**Issue by twastvedt** [Urigo/meteor-angular2.0-socially#30]
I'm working through the wonderful tutorial and have just one (non critical) issue I can't figure out. Everything is building fine, but Atom is highlighting some of my import lines, for example:
`import {Parties} from 'collections/parties';`
It finds the angular2 modules, and it's ok with the others if I add a `../` to the path. This looks a lot like #14, but I did the suggestions there because they were added to the tutorial:

``` json
"compilerOptions": {
  "experimentalDecorators": true,
  "module": "system",
  "target": "es5"
},
"files": [
  "typings/angular2-meteor.d.ts",
  "typings/party.d.ts",
  "client/app.ts",
  "server/main.ts"
]
```

I've tried restarting Atom, and letting Atom create its own `tsconfig.json` file.

**Comment by barbatus** [comment]
Is this the issue only with `collections/parties`?
If wonder if the links like `import {PartyDetails} from 'client/party-details/party-details'` work for you?

**Comment by twastvedt** [comment]
Right. Atom doesn't like those either. Related to this (I think?), I'm also getting the error:
`The file --- is not included in the Typescript compilation context.`
at the top of the files that these imports link to (for example, `client/party-details/party-details.ts`). If I add a `filesGlob: ["**/*.ts"]` to my `tsconfig.json`, I can get Atom to parse those files, so I guess the above error is a pretty obvious side effect of the `import` links not working.

**Comment by ShMcK** [comment]
This `tsconfig.json` configuration worked for me.
1. First you want Atom to automatically rewrite the `tsconfig.json` file upon any changes. 
2. Enable Angular 2 specific features such decoratores, system.js, etc.
3. Load all `.ts` files
4. Let Meteor handle loading of `.ts` files rather than Atom compiling them to `.js`.

``` js
{
 "atom": {
    "rewriteTsconfig": true
  },
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "system",
    "target": "es5",
    "moduleResolution": "classic"
  },
  "filesGlob": [
    "**/*.ts"
  ],
  "files": [],
  "compileOnSave": false,
  "buildOnSave": false,
}
```

**Comment by twastvedt** [comment]
@ShMcK Thanks, that makes sure Atom analyzes all the files. I still get the errors on the import statements though. In the end, it doesn't really matter, I can just ignore them if they're inevitable.

**Comment by ShMcK** [comment]
Yes, maybe there's a way to get atom-typescript to scan system.js modules. I'll post an issue.

**Comment by ShMcK** [comment]
Issue resolved. I've edited the solution above.

Add:

```
"compilerOptions": {
    "moduleResolution": "classic",
}
```

Thanks @basarat for solving [this issue](https://github.com/TypeStrong/atom-typescript/issues/814).
