### ISSUE TITLE
Some Tutorial Issues

### ISSUE THREAD

**Issue by barbatus** [Urigo/meteor-angular2.0-socially#31]
Some issues from @ShMcK:

Step 7:

```
 ***** New typings have been added *****
typings/meteor-accounts-ui.d.ts
***** Please re-start your app *****
```

Why not just automatically restart Meteor in the package?

`Parties.allow`, it would be better to pass in the type of Party rather than Object
Reference paths in `meteor-accounts.d.ts` don't match up.

```
/// <reference path="../../../typings/angular2.d.ts" />
/// <reference path="../../../typings/meteor/meteor.d.ts" />
/// <reference path="../../../typings/es6-promise/es6-promise.d.ts" />
```

Also, the general typings setup is FOLDER-NAME/FOLDER-NAME.
It might be better to hold this convention for angular2-meteor typings.

Step 8:

It starts using MeteorComponent. I'm not sure how or if MeteorComponent is still used.

**Comment by ShMcK** [comment]
I'll break these into smaller issues and try to explain them better.
