### ISSUE TITLE
Typings Cleanup

### ISSUE THREAD

**Issue by ShMcK** [Urigo/meteor-angular2.0-socially#32]
There are quite a few TypeScript conventions we should try to follow.
- More use of typings would be helpful.

```
party: Party // (only partially implemented)
parties: Party[]
Mongo.Cursor<Meteor.User>
var parties: Party[] // in load_parties.ts
```
- End each type with a semi-colon instead of a comma.

``` ts
declare type Party = {
  _id?: string;
  name: string;
  description?: string;
 ...
}
```
- Choose interfaces over types when referring to an object that may change.

``` ts
/* declare type Party = { */
interface Party {
  _id?: string;
  name: string;
  description?: string;
 ...
}
```
- Load library typings inside of a folder. For example:

```
|\ typings
    |- ng2-pagination
         \- ng2-pagination.d.ts
```

Other files that could follow this convention are `angular2-meteor.d.ts`, `angular2.d.ts`, `meteor-accounts.d.ts`, & `meteor-accounts-ui.d.ts`.
- Ensure reference paths point to the correct loaded path from the typings directory.

/meteor-accounts.d.ts

``` ts
/* /// <reference path="../../../typings/angular2.d.ts" /> */
/// <reference path="../angular2/angular2.d.ts" />
```
- We could consider targeting a set of standard conventions with [ts-lint](https://github.com/palantir/tslint).

**Comment by barbatus** [comment]
Interfaces are considered as fixed set of fields/methods, optional fields are now allowed in there.
And in general, `Party` seems more like a type (intuitively) than an interface.

**Comment by ShMcK** [comment]
I believe in TypeScript, as opposed to C#, interfaces outline the APIs. Based on the TS Handbook, they can include [optional properties](http://www.typescriptlang.org/Handbook#interfaces-optional-properties), whereas types focus on primitive values like Boolean, Number, etc.

> One of TypeScript's core principles is that type-checking focuses on the 'shape' that values have. This is sometimes called "duck typing" or "structural subtyping". In TypeScript, interfaces fill the role of naming these types, and are a powerful way of defining contracts within your code as well as contracts with code outside of your project.

**Comment by barbatus** [comment]
Hm, I seem to have imagined it wrongly somehow. Ok, I'll convert Party to an interface.
