### ISSUE TITLE
Automatically Reload Meteor on Package First Run

### ISSUE THREAD

**Issue by ShMcK** [Urigo/meteor-angular2.0-socially#34]
Several packages from the tutorial must be re-run in order to be initialized. You can see this from the console.

```
 ***** New typings have been added *****
typings/meteor-accounts-ui.d.ts
***** Please re-start your app *****
```

Why not just automatically restart Meteor during package initialization?

`ng2-pagination` must also be restarted.

**Comment by zayau** [comment]
When should I expect official angular2 upgrade on atmosphere? Or angular2 will install via npm in Meteor 1.3?
