### ISSUE TITLE
Angular 2.0 Errors when deploying this (minifying i guess or even meteor --production)

### ISSUE THREAD

**Issue by jeveloper** [Urigo/meteor-angular2.0-socially#36]
First of all, Thank you Uri for all your hard work!

Not sure if this helps:
osx
node 5.5

running meteor --production 

the app wont load due to errors right off the bat. Any chance someone can help, i built my app by following meteor tutorial and am unable to deploy it anywhere. 

I did see a message here:
"=> A patch (Meteor 1.2.0.2) for your current release is available!
   Update this project now with 'meteor update --patch'."

But in my other project i am using the latest 1.2.1 and seeing other errors also probably due to minification.

No Directive annotation found on e
259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:94 EXCEPTION: No Directive annotation found on et.logError @ 259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:94
259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:94 STACKTRACE:t.logError @ 259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:94
259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:94 Error: No Directive annotation found on e
    at new t (http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:76:30282)
    at e.resolve (http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:76:15303)
    at e.getResolvedDirectiveMetadata (http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:78:24895)
    at Function.e.create (http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:77:30985)
    at eval (viewFactory_p:1039:37)
    at Object.I [as evalExpression](http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:72:19961)
    at e._createViewFactoryRuntime (http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:95:20901)
    at http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:95:19560
    at n.o [as run](http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:72:4547)
    at n.run (http://localhost:3000/259f0e0b966c530f8690d42abf047e593ca0e661.js?meteor_js_resource=true:83:26257)

**Comment by barbatus** [comment]
Yes, there are some issues with JS uglification introduced in 2.0.0-beta.1.
For example, https://github.com/angular/angular/issues/6380.
I just tested it with 2.0.0-beta.0 and found no errors.
Let's wait till beta.2.

**Comment by jeveloper** [comment]
Thank you for response Alex, i just checked notes on beta2 and it too has the same problem.
Ill continue with dev mode :) 
hope it'll be resolved

**Comment by dragGH102** [comment]
same problem here with the very latest beta (I guess - I started the tutorial 1 week ago).
Any way to eventually deploy the app to Galaxy (or other cloud provider) **without** minifying/uglify?

**Comment by jeveloper** [comment]
Workaround:

Set uglify.mangle to false for now.

**Comment by mjwheatley** [comment]
@jeveloper where and how do you use the uglify.mangle setting?
I removed the standard-minifiers package for the time being.  That allowed me to use MUP to deploy to my test server at least.

**Comment by jeveloper** [comment]
Hey Mathew, 
What i'm proposing is directly changing code of the module, which is terrible.

**Comment by abrass** [comment]
@jeveloper 
Sorry, I'm new, where exactly did you change the value? I know changing the module code is bad, but for now I'm trying around, so fine with that :)

In Angular-1 there was ngAnnotate to avoid this problem with minifying using Grunt

**Comment by jeveloper** [comment]
Actually i would go with removing standard-minifiers

**Comment by dragGH102** [comment]
I believe the best option is to allow customization during deploy (or local
run with - production flag).
minimization and uglification are per se good and I'd say the "standard"
for production. however when learning new technologies to be eventually
used in production in the near future can really be a pain.
Please refer to the issue on Meteor repo, since it's a Meteor related issue
they'll definitely put more attention there than projects using Meteor.
any other idea?

**Comment by hongbo-miao** [comment]
Hi @dragGH102 
You can track here, Meteor side: https://github.com/angular/angular/issues/6380
Uglify side: https://github.com/mishoo/UglifyJS2/issues/999

**Comment by felicedeNigris** [comment]
So is this a angular-with-blaze and uglify 'standard-minifiers' packages not working together? I am having some hard times deploying to galaxy and modulus with minification errors? So I unistalled standard-minifiers and I am redeploying, but it is taking forever!!

**Comment by Hongbo-Miao** [comment]
@jeveloper I ran `meteor remove standard-minifiers` first, then the program can runs well using `meteor —-production`, but once I deployed on heroku, it still shows 
> EXCEPTION: No Directive annotation found on e
Where did you deploy? Thanks

**Comment by barbatus** [comment]
Might help https://github.com/Urigo/angular2-meteor#it-works-fine-locally-but-fails-to-run-in-the-production

**Comment by allanlundhansen** [comment]
@Hongbo-Miao does Heroku is not run its own minifier, that was the case with Modulus at least once I deployed with -D it works fine with them, not sure how Heroku handle it though.

**Comment by barbatus** [comment]
Fixed in beta-16.

**Comment by jeveloper** [comment]
@barbatus It appears that angular2-meteor hasnt been published to atmospherejs in a while, its at version 0.5.2 
https://atmospherejs.com/urigo/angular2-meteor

can you publish 0.5.4 with beta 16 or 17 of angular please?

thank you

**Comment by Urigo** [comment]
@jeveloper why aren't you using `angular2-meteor` from npm?

**Comment by jeveloper** [comment]
I apologize i will from now

**Comment by Urigo** [comment]
no need to apologize :)

**Comment by FlawaCLV** [comment]
What is the proper configuration to make **standard-minifier-js** works ? Because it's been more than a year that I can't publish minified code to production... Still have `Error: No provider for e!` !
