### ISSUE TITLE
Source code for steps5+ of meteor-angular2.0-socially?

### ISSUE THREAD

**Issue by dragGH102** [Urigo/meteor-angular2.0-socially#4]
I noticed that in the tutorial ( http://angular-meteor.com/tutorials/angular2/routing-and-multiple-views ) there are several errrors (especially on files name).
Now I'm stuck, but despite live version of each step is available, the no source for each step (nor for last one).

Any way it's possible to have them?

**Comment by newswim** [comment]
Same here, even cloning the example repo throws several errors which seem to involve Meteor's internal use of modules and modules as used by the typescript package. I wonder if something like https://atmospherejs.com/rocket/module could serve as a kind of shim for this step? I wish we could just use es6 with angular 2 and be done already (heh).

**Comment by U1F984** [comment]
https://angular-meteor.com/tutorials/angular2/3-way-data-binding is not accessible for me at all (shows blank page, accessing via navigation doesn't work).

**Comment by fodurrr** [comment]
Same for me as well. https://angular-meteor.com/tutorials/angular2/3-way-data-binding not accessible, sometimes if I click on the site on the Angular 2.0 button then it brings up the Angular 1 version for chapter 3.

**Comment by ShMcK** [comment]
The tutorial is currently changing over to use `urigo:angular2-meteor`. It's currently only updated to step 4 I believe. You can find a working example of the tutorial [here](https://github.com/Urigo/Meteor-Angular2).

In the meantime, you may want to use the [tutorial docs](https://github.com/Urigo/angular-meteor/tree/master/.docs/angular-meteor/client/content/tutorials/angular2/steps) for step 3. The git diff tutorial throws an error any time multiple files are committed, I've seen this issue before.

**Comment by ShMcK** [comment]
@barbatus Issue seems to be [this commit](https://github.com/barbatus/angular-meteor/commit/6856216ccc72885f1d35739018311481c80526d6). Step 3.4 is missing. Should be a quick fix.

**Comment by barbatus** [comment]
@ShMcK yes I noticed it too, this PR https://github.com/Urigo/angular-meteor/pull/776 contains the fix, thanks

**Comment by Urigo** [comment]
It's live here: http://angular-meteor.com/tutorials/angular2/3-way-data-binding
Thanks @barbatus
