### ISSUE TITLE
Meteor Tracker typings not found using Tutorial steps

### ISSUE THREAD

**Issue by Splaktar** [Urigo/meteor-angular2.0-socially#41]
Here is the result of following the current version of the [tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding):
![screen shot 2016-01-30 at 5 10 42 pm](https://cloud.githubusercontent.com/assets/3506071/12698812/486c03ce-c775-11e5-9851-3e137a9cab13.png)

Error in Console:

```
client/app.ts (17, 9): Cannot find name 'Tracker'.
```

To fix this, I needed to do the following:
1. `sudo npm install -g typings`
1. `typings install meteor --ambient`
1. Modify `typings/angular2-meteor/angular2-meteor.d.ts` to change the second line from

```
/// <reference path="../meteor/meteor.d.ts" />
```

To:

```
/// <reference path="../main.d.ts" />
```

Note that `main.d.ts` has the following contents:

```
/// <reference path="main/ambient/meteor/meteor.d.ts" />
```

I didn't see a clear way to make a PR to fix this.

**Comment by barbatus** [comment]
Yes, most typings are available on [DefinitelyTyped](http://definitelytyped.org/), so the right way will be to install them from there. From other side, custom typings created for packages or declaration files that are distributed via NPM packages (like Angular 2) will be installed by Angular2-Meteor and other packages.

In order to install Meteor typings, you will need to run:

```
npm install tsd -g
tsd install meteor
```

**Comment by Splaktar** [comment]
tsd was officially deprecated in favor of Typings earlier this week. I think that using the --ambient flag in Typings allows it to grab the definitions from DefinitelyTyped.

**Comment by barbatus** [comment]
yes, you're right, I am fixing it to be `typings` instead. thx for pointing that out.

**Comment by Splaktar** [comment]
No problem. It's crazy how fast things change and get deprecated :) Thank you for your effort!
