### ISSUE TITLE
Use ng2-pagination

### ISSUE THREAD

**Issue by Urigo** [Urigo/meteor-angular2.0-socially#42]
Right now we are using our own pagination module.

Instead we should bring [ng2-pagination](https://github.com/michaelbromley/ng2-pagination) from Npm and contribute to it.

The problem is the currently with Angular 2.0 we can't use our custom [Mongo differ](https://github.com/Urigo/angular2-meteor/blob/master/modules/mongo_cursor_differ.ts) before a pipe (that ng2-pagination is using).
The Angular issue is tracked here - https://github.com/angular/angular/issues/6757

**Comment by jeveloper** [comment]
Thanks Urigo !

Any way you can remove the dependency on totalsize when fetching via server side , clearly counter is not a good practice 
It would be nice to have just <prevous> <next>

Thanks!

**Comment by Urigo** [comment]
@jeveloper how would you do pagination without the number off all documents?

**Comment by jeveloper** [comment]
I'm thinking just make it <prev> <next>  and last one that has any data is the last page.
This counter thing will kill performance since it can't be easily optimized for real time. 
What do you think?

**Comment by Urigo** [comment]
done in the new and updated tutorial
thanks @kamilkisiela
