### ISSUE TITLE
Add chapter on Bootstrap CSS

### ISSUE THREAD

**Issue by Urigo** [Urigo/meteor-angular2.0-socially#44]
If someone is trying, try to use the Angular2-Meteor 0.5.0-beta and bring Bootstrap from Npm

**Comment by Hongbo-Miao** [comment]
Hi @Urigo , I already created an issue on ng2-bootstrap's github. It is here:

https://github.com/valor-software/ng2-bootstrap/issues/114

**Comment by Hongbo-Miao** [comment]
Another issue https://github.com/valor-software/ng2-bootstrap/issues/129

**Comment by hongbo-miao** [comment]
Hi @Urigo , Bootstrap in angular2-meteor1.2.1 just one step, install [this package](https://atmospherejs.com/zrbfly/ng2-bootstrap), and then it works.

I tried to add ng2-bootstrap in angular2-meteor1.3.

First I did [these steps](https://github.com/Urigo/angular2-meteor/issues/180) to create a project.
Then I ran `npm install ng2-bootstrap --save` to install [ng2-bootstrap](http://valor-software.com/ng2-bootstrap/), but the page still has no style. I am not sure how to `import` ng2-bootstrap correctly actually.

@dotansimha created [this issue](https://github.com/Urigo/angular2-meteor/issues/126). It is about Bootstrap, so I am not sure it is related with ng2-bootstrap or not.

**Comment by Urigo** [comment]
@Hongbo-Miao good point. I think we will have the Socially 2.0 with Meteor 1.3 and Bootstrap up very soon.
It's without ng2-bootstrap but I would love help with that.
Let's wait a few days for the first version to be out and then let's try to work with them to add it.
I believe they had a few issues back when we tried initially.

**Comment by Urigo** [comment]
maybe create a separate issue for using `ng2-bootstrap` and not just the CSS

**Comment by hongbo-miao** [comment]
@Urigo where should I create this issue?
https://github.com/Urigo/meteor-angular2.0-socially
https://github.com/Urigo/angular2-meteor
or https://github.com/valor-software/ng2-bootstrap

**Comment by hongbo-miao** [comment]
Oh, just saw last message, I will wait until Socially 2.0 with Meteor 1.3 and Bootstrap comes up! Getting excited

**Comment by dotansimha** [comment]
With the new Meteor 1.3 tutorial we have this chapter!! With the latest beta of Bootstrap 4!! Awesome!!
