### ISSUE TITLE
how to import and use with 3rd party module(form npmjs, ngmodules.org)

### ISSUE THREAD

**Issue by www2341** [Urigo/meteor-angular2.0-socially#46]
Hi.
I'm just new in web. 

I was looking for a way of uploading file to server, there is tutorial for only angular1 meteor.
so I want to know how to import and use 3rd party modules. 
If tutorial provided soon, I think I need import and use 3rd party modules.
Is there any document? or blogs? or is it same to chaper 19 on angular1 meteor tutorials.

Also I'm just wondering about should I study with angular1-meteor instead angualr2-meteor.
because I think tip, document and community isn't enough for beginner. 
which one is better on beginner of web??

**Comment by jeveloper** [comment]
Actually Angular 2 is here to stay , its already in beta 3, Urigo has a fairly great angular2- meteor tutorial.

3rd party modules ? If you're talking about nodejs modules , all you need is "meteorhacks:npm" , then you can use any module.

If you're talking about regular javascript libraries , just add them to client folder and they'll be available or to lib directory or use reference to CDN.

**Comment by www2341** [comment]
Thanks, you make me clear!!
