### ISSUE TITLE
namespace problems / Error during instantiation of SebmGoogleMap

### ISSUE THREAD

**Issue by universalien** [Urigo/meteor-angular2.0-socially#47]
your application is not installable.

C:\ ... \meteor\meteor_angular2>meteor
...
collections/methods.ts (3, 32): Cannot find namespace 'Meteor'.
collections/methods.ts (10, 1): Cannot find name 'Meteor'.
collections/methods.ts (12, 9): Cannot find name 'check'.
collections/methods.ts (13, 9): Cannot find name 'check'.
collections/methods.ts (18, 23): Cannot find name 'Meteor'.
collections/methods.ts (21, 23): Cannot find name 'Meteor'.
collections/methods.ts (24, 23): Cannot find name 'Meteor'.
collections/methods.ts (29, 40): Cannot find name 'Meteor'.
collections/methods.ts (30, 38): Cannot find name 'Meteor'.
collections/methods.ts (32, 17): Cannot find name 'Meteor'.
collections/methods.ts (33, 17): Cannot find name 'Email'.
collections/methods.ts (39, 50): Cannot find name 'Meteor'.
collections/methods.ts (45, 9): Cannot find name 'check'.
collections/methods.ts (46, 9): Cannot find name 'check'.
collections/methods.ts (49, 23): Cannot find name 'Meteor'.
collections/methods.ts (52, 23): Cannot find name 'Meteor'.
collections/methods.ts (57, 23): Cannot find name 'Meteor'.
collections/methods.ts (60, 23): Cannot find name 'Meteor'.
collections/methods.ts (63, 23): Cannot find name 'Meteor'.
collections/methods.ts (69, 17): Cannot find name 'Meteor'.
collections/parties.ts (1, 26): Cannot find name 'Mongo'.
collections/parties.ts (5, 16): Cannot find name 'Meteor'.
collections/parties.ts (9, 16): Cannot find name 'Meteor'.
collections/parties.ts (13, 16): Cannot find name 'Meteor'.
server/parties.ts (31, 1): Cannot find name 'Meteor'.
server/parties.ts (37, 1): Cannot find name 'Meteor'.
server/users.ts (3, 1): Cannot find name 'Meteor'.
server/users.ts (7, 19): Cannot find name 'Meteor'.
server/users.ts (9, 12): Cannot find name 'Meteor'.
server/main.ts (6, 1): Cannot find name 'Meteor'.
=> Meteor server restarted
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

in firebug:

EXCEPTION: Error during instantiation of SebmGoogleMap!.

**Comment by universalien** [comment]
perhaps this is a cause (but not the solution):
https://gitter.im/SebastianM/angular2-google-maps/archives/2016/01/12

**Comment by barbatus** [comment]
It was fixed long time ago, try to update the maps package: `meteor update barbatus:ng2-google-maps`. In general, update packages before running the app.
