### ISSUE TITLE
Angular 2.0 Routing - refreshing /party/partyId URL

### ISSUE THREAD

**Issue by deltaag** [Urigo/meteor-angular2.0-socially#49]
After adding routing in step 5, if I click on a party, app routes to `localhost:3000/party/<partyId>` and shows the party detail and all works fine. But if I refresh that URL (or try loading the URL in a new tab), I get a blank page.
Is this normal, or I am missing something?

**Comment by barbatus** [comment]
You are missing something, it works fine for me. Try to fork the repo or download the latest app version and run it.

**Comment by deltaag** [comment]
Thanks Alex,
The problem was templateUrl should start with / as in: `'/client/party-details/party-details.html'`

Digging in Angular 2.0 website, they are using `name:` instead of `as:` in `@RouteConfig` array, and `[routerLink]` directive's link parameter doesn't need / as in: `[routerLink]="['PartyDetails', {partyId: party._id}]"`
Not sure if any of these are important. Currently the code in angular 2.0 socially works perfectly.

**Comment by the-evgenii** [comment]
i have this problem too

fix:
`templateUrl: '/client/app.html'` instead `templateUrl: 'client/app.html'` in app.ts

**Comment by sunshineo** [comment]
As of today (6/2/2016), I downloaded the latest meteor, latest code of this repository and this problem still exists. The templateUrl is already /client/app.html
The empty page is a little bit different though. It has the banner now.
