### ISSUE TITLE
Angular 2.0 Chapter3 is not accessible

### ISSUE THREAD

**Issue by fodurrr** [Urigo/meteor-angular2.0-socially#5]
https://angular-meteor.com/tutorials/angular2/3-way-data-binding
Unfortunately this chapter is not accessible, I am stuck. :((

**Comment by ShMcK** [comment]
There seems to be an issue. Perhaps you could use the docs on Github in the meantime: https://github.com/Urigo/angular-meteor/tree/master/.docs/angular-meteor/client/content/tutorials/angular2/steps

**Comment by fodurrr** [comment]
thanks, it is working now.

**Comment by simonv3** [comment]
Have certificates expired? @Urigo?

**Comment by Urigo** [comment]
Yes I should upload the site to Galaxy and get certificates..
After AngularConnect

**Comment by simonv3** [comment]
Lets Encrypt might be available by now, dunno how that plays with Galaxy.
