### ISSUE TITLE
meteor deploy step_05   Not work

### ISSUE THREAD

**Issue by xiaofeihe** [Urigo/meteor-angular2.0-socially#50]
root@hui:~/dev/meteor-angular2.0-socially# git checkout step_05 -f
HEAD 目前位于 dc9e092... Adds RouterLink dependency.
root@hui:~/dev/meteor-angular2.0-socially# meteor -p 3004
[[[[[ ~/dev/meteor-angular2.0-socially ]]]]]  

=> Started proxy.  
=> Started MongoDB.  
=> Started your app.                          

=> App running at: http://localhost:3004/

**it work**

**But** 

`meteor deploy wvapp.meteor.com`

**Not work**

GO     http://wvapp.meteor.com/

**Comment by barbatus** [comment]
duplicated https://github.com/Urigo/meteor-angular2.0-socially/issues/36
