### ISSUE TITLE
Blank screen on Android Emulator

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Urigo/meteor-angular2.0-socially#51]
Hi! I cloned the repo and tried to run it on my android emulator (I use Genymotion)

```
meteor run android-device
```

It successfully build on my Emulator but all I see is a blank screen.
Although, It is working on browser
Google Galaxy Nexus 4.2.2 - API 17

**Comment by Urigo** [comment]
@rafaelcorreiapoli can you try this with the latest Meteor 1.3 beta?

**Comment by rafaelcorreiapoli** [comment]
@Urigo  It still does not work

**Comment by rafaelcorreiapoli** [comment]
I tried with

```
--release 1.3-beta.11
```

Now the project does not work even on browser, I get these errors:

```
Uncaught TypeError: Cannot read property 'match' of undefined
Uncaught TypeError: Cannot read property 'System' of undefined
Uncaught TypeError: Cannot read property 'System' of undefined
Uncaught TypeError: Cannot read property 'System' of undefined
Uncaught TypeError: Cannot read property 'System' of undefined
Uncaught TypeError: Cannot read property 'System' of undefined
Uncaught ReferenceError: System is not defined
Uncaught ReferenceError: System is not defined
Uncaught ReferenceError: System is not defined
Uncaught ReferenceError: System is not defined
Uncaught ReferenceError: System is not defined
```

**Comment by Urigo** [comment]
I think I understand the situation, looking in to it

**Comment by rafaelcorreiapoli** [comment]
Nice :) im really excited to test ionic2 :)

**Comment by rafaelcorreiapoli** [comment]
@Urigo 
have you been able to solve the problem ?

**Comment by codetravis** [comment]
I am interested in this issue as well.  Having the same problem with a project I am working on.  Tried every solution I could find so far. Getting same errors (undefined match then undefined system).

**Comment by codetravis** [comment]
Update: Late last night/ early this morning after trying upgrading everything to 1.3 beta and no success, I downgraded back to 1.2 and then removed Accounts and AccountsUI packages from tutorial and it started working.  Something about the current Angular 2 integration for the barbatus:ng2-meteor-accounts and barbatus:ng2-meteor-accounts-ui does not play well with android.  I did notice later in the tutorial there is a packaging section that deals with splitting the login functions to be different for the web and phone deploys, will look into using this.

**Comment by barbatus** [comment]
I just tried running `meteor run android-device` using Genymotion emulator,  Meteor 1.3 and Android API 23. It's slow but works as expected. So please try with Meteor 1.3 and API 23.

<img src="https://cloud.githubusercontent.com/assets/2824096/14226547/402710e6-f8ee-11e5-8e71-3c1d6bc7e744.png" width="400">
