### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by aayushkapoor206** [Urigo/meteor-angular2.0-socially#52]
The tutorial would be really helpful if there were screenshots accompanying it. I got really confused near the Ionic part and wished for screenshots to guide me.

**Comment by Urigo** [comment]
screenshots of the app itself?

**Comment by aayushkapoor206** [comment]
@Urigo Yes 😄

**Comment by debovema** [comment]
+1
Or a live demo site.
There are a lot of issues when we run the project from scratch that it would be good to see the expected result.

**Comment by Urigo** [comment]
We just added video demo when you click the "Live Demo" button.
Is it good enough?
