### ISSUE TITLE
migrate from mongoDB to Mysql angular2-meteor

### ISSUE THREAD

**Issue by tawfik91** [Urigo/meteor-angular2.0-socially#55]
I'm working a project using Angular2-meteor with mongDB .

Now i am looking out for a solution to migrate data from mongodb to MySQL.

Please let me know if there are any solutions for the same.

Thank you.

**Comment by u0m3** [comment]
As far as I know there is no official support for other databases in meteor besides MongoDB.
That being said, a bit of googling revealed [Reactive MySQL for Meteor](https://github.com/numtel/meteor-mysql) which at a first glance seems to do what you require.

Hope this helps in some way.

**Comment by tawfik91** [comment]
thank you for this response ,

i want for typescript solution .

**Comment by barbatus** [comment]
If you are asking for an alternative to MongoDB, you've been told one.
Otherwise, I don't see how your question is related to the Socially app and TypeScript.
So closing. if still have question directly related to the Socially, please elaborate and re-open this issue.

**Comment by Urigo** [comment]
Thanks for the comments.
also for questions like those, I think the [Meteor forums](https://forums.meteor.com/) are the best for those

**Comment by tawfik91** [comment]
thanks for all .
urigo i have posted but no response that's why i posted here
