### ISSUE TITLE
Incomplete okland:accounts-phone twilio integration 

### ISSUE THREAD

**Issue by mintymac** [Urigo/meteor-angular2.0-socially#56]
From Step 21: : http://www.angular-meteor.com/tutorials/socially/angular2/mobile-support-and-packages-isolation

@Urigo Thank you for putting this tutorial together.  
I'm not sure of the best(any) way to have socially pull in the settings vars for use in socially.   

```
{
  "TWILIO": {
    "FROM": "+15125551212",
    "SID": "XXXXXXXX",
    "TOKEN" : "XXXXXXXXXXX"
  },
  "ACCOUNTS_PHONE": {
    "ADMIN_NUMBERS": ["+15125551212"],
    "MASTER_CODE": "1234"
  }

}
```

In your whatapp meteor clone, you used something like this that made SMS.twilio available to accounts-phone .   What are your thoughts on how to finish this?  And I apologize if this is discussed somewhere I did not see.   Cheers,

MM

**Comment by Urigo** [comment]
@mintymac could you PR the docs of the tutorial to mention that and link to the package explanation?

**Comment by dotansimha** [comment]
Hi @mintymac , 
Please note that we are using another package in the tutorial - `mys:accounts-phone`.
Also, since March the tutorial changed a lot and I think this issue might not be relevant.

Please reopen the issue if you still have issues. 

Thanks.
