### ISSUE TITLE
Cannot find namespace 'Mongo'  and Cannot find name 'Meteor'

### ISSUE THREAD

**Issue by robertlight** [Urigo/meteor-angular2.0-socially#57]
using: meteor v1.2.1
# I was getting these three error messages on startup:

```
[web.browser] client/parties-list/parties-list.ts (17, 14): Cannot find namespace 'Mongo'.
[web.browser] collections/parties.ts (2, 26): Cannot find name 'Mongo'.
[os.osx.x86_64] server/main.ts (6, 1): Cannot find name 'Meteor'.
```

Ultimately, by by adding the following line to my tsconfig.json files array, I was able to get the error messages to go away:

```
    "typings/main.d.ts",
```

Note that functionally, everything was working fine.

**Comment by aaronksaunders** [comment]
running into same issue using Meteor 1.3

**Comment by Urigo** [comment]
related to this - https://github.com/Urigo/meteor-angular2.0-socially/issues/45#issuecomment-203676744

**Comment by barbatus** [comment]
`tsconfig.json` in the root of this repo has line `typings/main.d.ts` added to the files. I don't why it was s surprise for you.

**Comment by pubkey** [comment]
@barbatus thanks that worked.
