### ISSUE TITLE
html template cache not working flawlessly

### ISSUE THREAD

**Issue by robertlight** [Urigo/meteor-angular2.0-socially#58]
I have found that my .html template files aren't getting uploaded properly.

I've had to resort to using the following:

``` javascript
@View({
    templateUrl: '/client/parties-list/parties-list.html?defeat_cache='+(new Date()).getTime(),
    directives: [PartiesForm, RouterLink]
})
```

to reliably get my changes to overcome the cached templates.

Am I missing something?  Am I tickling a bug somewhere?

**Comment by barbatus** [comment]
A duplicate of https://github.com/Urigo/angular2-meteor/issues/64
