### ISSUE TITLE
Step 0 - runing meteor dosent add the "typings" dir

### ISSUE THREAD

**Issue by ohadgk** [Urigo/meteor-angular2.0-socially#61]

**Comment by benlilo** [comment]
+1 Here. I use meteor 1.3.
Running meteor after 0.10 doesn't create a 'typing' folder nor a angular2-meteor.d.ts folder or a angular2-meteor.d.ts file. The typing file is actually later created by the 'npm install typings -g' command. 

I was able to continue without 'angular2-meteor.d.ts' file and to run the application without problem but I'm now stuck in 3.5 where the app crashes with these errors:

client/app.ts (15, 6): Cannot find name 'Tracker'.
collections/parties.ts (1, 26): Cannot find name 'Mongo'.

I'm a beginner and I still don't understand everything so I don't know if it has something to do with this issue.

Any help is welcomed.

EDIT: 
Problem solved following 'TypeScript Configuration and IDEs' at chapter 7. 
Now another one has showed up. The console shows the error 
**client/app.ts (13, 25): Cannot find name 'Object'.**
refering to the line  **parties: Mongo.Cursor<Object>;** in app.ts.

I really don't understand ! What am I missing ?
Thanks!

**Comment by benlilo** [comment]
@Urigo could you give us a hand here ? 
I tried but still don't find any solution, and I can't even start to understand where the error is coming from.
Thank's !

**Comment by Urigo** [comment]
at the end of the chapter there is an explanation with this link - https://gist.github.com/tomitrescak/8366ce98f1857e202ea8
please let me know if that fixed it for you

**Comment by Urigo** [comment]
please try the new updated tutorial and let me know if that worked for you
