### ISSUE TITLE
Step 7 - "TypeScript Configuration and IDEs" Instructions Missing

### ISSUE THREAD

**Issue by derek-fong** [Urigo/meteor-angular2.0-socially#62]
In [Step 7](http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure) of the tutorial, 

**TypeScript Configuration and IDEs**

```
...
To fix plugins, let's set up our tsconfig.json properly with the options that will make plugins understand our needs and the structure of our app.
```

> // Instructions to modify `tsconfig.json` is missing here. 

```
Now, let's go to any of the .ts files and check if all that annoying redness has disappeared.
```

**Comment by stefanholzapfel** [comment]
Yep that is missing.

And just some steps before (point 7.4) you are advising to change the type of the generic collection from "object" to "party", but in your example code the collection isn't generic at all?

And if i make it generic it is working, but i get the error from my IDE (WebStorm), that type mongo.cursor is not generic....

**Edit:**
In 7.3 you also forgot to update the code from
`export var Parties = new Mongo.Collection('parties');`
to
`export var Parties = new Mongo.Collection<Party>('parties');`

**Comment by nooralsbah** [comment]
Hi 
I followed all the steps in step 7
but I'm getting this error.

`/Users/nooralsbah/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
                        throw(ex);
                              ^
Error: A method named '/parties/insert' is already defined
    at packages/ddp-server/livedata_server.js:1548:15
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at Server.methods (packages/ddp-server/livedata_server.js:1544:7)
    at packages/allow-deny/allow-deny.js:191:24
    at [object Object].CollectionPrototype._defineMutationMethods (packages/allow-deny/allow-deny.js:190:5)
    at new Mongo.Collection (packages/mongo/collection.js:226:8)
    at meteorInstall.collections.parties.js (collections/parties.ts:3:22)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at server/main.ts:4:29
Exited with code: 8
Your application is crashing. Waiting for file change.`

What am I doing wrong here?

**Comment by kamilkisiela** [comment]
@nooralsbah 

```
Error: A method named '/parties/insert' is already defined
```

So maybe there is a copy of file with Method definition or you just defined this method twice.

**Comment by nooralsbah** [comment]
Yas thank you Kamil
 I delete all failes that's end with .js and . map.js

**Comment by kamilkisiela** [comment]
Great! :tada:

**Comment by dohomi** [comment]
@derek-fong did you finally solve the issue with the Webstorm message? I'm going through the steps and don't get rid of it either

**Comment by kamilkisiela** [comment]
@dohomi I just updated the tutorial. It looks fine when it comes to `barbatus:typescript` compiler and also inside Atom IDE.

Could you check it again? Also, after which step you see those warnings? Is it the last one?

**Comment by kamilkisiela** [comment]
@derek-fong Urigo/angular-meteor-docs#144 should fix it

**Comment by dohomi** [comment]
@kamilkisiela for me it didn't work. Not sure if Webstorm behaves different. I even checked out this github repo and opened it in Webstorm with the same error.

**Comment by dohomi** [comment]
this are my settings. I won't compile through Webstorm otherwise the files are getting generated, am I right with this?
<img width="795" alt="screen shot 2016-06-02 at 22 53 52" src="https://cloud.githubusercontent.com/assets/489221/15749457/06ffcc5c-2915-11e6-81f2-3ab7e6540e56.png">

**Comment by kamilkisiela** [comment]
@dohomi It's good to turn off `compileOnSave` etc. settings, we don't need .js and .js.map files.

About "didn't work". I just fixed that missing instructions which the author of this issue had noticed.

I'm using the Atom and I don't see any warnings but give me some time to install WebStorm, so maybe I could help you! :sos:

**Comment by dohomi** [comment]
@kamilkisiela thanks! Well I'm using Webstorm because usually everything works out of the box.. beside this time :)

**Comment by kamilkisiela** [comment]
@dohomi  Here's a [screenshot](http://i.imgur.com/GhBcduT.png) of my TypeScript settings (by default, haven't change anything) in WebStorm.

It shows only one warning but it will be fixed by Urigo/angular2-meteor-accounts-ui#15

**Comment by dohomi** [comment]
strange. Ok I will work on some of the `redish` is my fault I just fixed most of them. A last one is the use of 

```
@Component({
    moduleId: module.id,
    (...)
})
```

Inside of any Component for relative paths. Its not part of socially but do you know anything about it and how to tell `meteor-angular2` to enable relative paths?

**Comment by kamilkisiela** [comment]
@dohomi Something like this works for me:

``` ts
// client/app.ts
@Component({
  selector: 'app',
  moduleId: module.id,
  templateUrl: 'app.html',
})
```

**Comment by dohomi** [comment]
I works well for me as well, but I receive:

```
userEdit.ts (14, 15): Cannot find name 'module'.
```

Inside of the console. It compiles correctly though..

**Comment by kamilkisiela** [comment]
@dohomi Try this:

``` bash
typings i -SA node
```

Which will install typings of node and save them as ambientDependency.

If you don't have `typings` installed:

``` bash
npm i -g typings
```

**Comment by dohomi** [comment]
I have typings already installed as recommended by this tutorial. Inside Webstorm and the console output I receive this error.

**Comment by kamilkisiela** [comment]
@dohomi Yes, but did you install typings for `node` to use `module.id`?

**Comment by dohomi** [comment]
I haven't seen any documentation about this. This is my typings so far:

```
{
  "name": "pt-test",
  "dependencies": {
    "es6-promise": "registry:npm/es6-promise#3.0.0+20160211003958",
    "lodash": "registry:npm/lodash#4.0.0+20160416211519"
  },
  "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654"
  }
}

```

**Comment by dohomi** [comment]
Ok I added node into the globalDependencies.. now it works all good! Thanks for your help @kamilkisiela !

**Comment by kamilkisiela** [comment]
@dohomi Fantastic!
