### ISSUE TITLE
party.d.ts

### ISSUE THREAD

**Issue by admirkb** [Urigo/meteor-angular2.0-socially#63]
Easy one to fix...You just have duplicate entry for location

interface Party {
  _id?: string;
  name: string;
  description?: string;
  location: string;
  location: {
    name: string;
    lat?: number;
    lng?: number;
  };
  invited?: Array<string>;
  rsvps?: Array<RSVP>;
}

interface RSVP {
  userId: string;
  response: string;
}

**Comment by Urigo** [comment]
thanks!
fixed in the new deployed tutorial
