### ISSUE TITLE
meteor/tmeasday:publish-counts error

### ISSUE THREAD

**Issue by khwerhahn** [Urigo/meteor-angular2.0-socially#66]
In the tutorial 12 I keep getting the error displayed, that the module `'meteor/tmeasday:publish-counts'.` cannot be found. I did add it like in the tutorial described: 

`$ meteor add tmeasday:publish-counts`

and is imported with:

`import {Counts} from 'meteor/tmeasday:publish-counts';`

I'm using meteor 1.1.13

**Comment by Urigo** [comment]
the `import` statement only works on versions on Meteor newer than 1.3
