### ISSUE TITLE
Step 4.9: Why passing the values to addParty as parameter?

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/meteor-angular2.0-socially#69]
Hi!

This is rather a question than an issue, but i don't now another place to get in contact with you guys.

In Step 4.9 when writing the form value to mongodb, why are you passing it from the view via the local variable #f and not just take advantage of the data binding?

Why use 
`Parties.insert({
                name: party.name,
...
});`
and not
`Parties.insert({
                name: this.partiesForm.controls['name'].value,
...
});`
?

Thanks a lot!

Greetings,
Stefan

**Comment by Urigo** [comment]
no particular reason, I just feel like the current way is a bit cleaner, but it's just personal preference..
