### ISSUE TITLE
Steps 3.4, 3.5 and 3.6 seems to not be working

### ISSUE THREAD

**Issue by douglascorrea** [Urigo/meteor-angular2.0-socially#7]
If you follow the tutorial, the steps 3.4, 3.5 and 3.6 do not show anything on screen.

But if you put the load_parties and Meteor.startup() from the step 3.8 it work again.

It seems that if you don't "bootstrap" the Parties collection on the server side it not became available on client side.

Is that an Angular2 bug or something that is missing on the tutorial?

**Comment by aaronksaunders** [comment]
@douglascorrea - I am running into the same issue and I am blocked? Did you find a solution to help you move forward?

Also seeing error 

```
=> Client modified -- refreshingclient/app.ts (21, 14): Generic type 'Cursor<T>' requires 1 type argument(s).
=> Client modified -- refreshing (x2)client/app.ts (21, 14): Generic type 'Cursor<T>' requires 1 type argument(s).
=> Client modified -- refreshing (x3)client/app.ts (21, 14): Generic type 'Cursor<T>' requires 1 type argument(s).
=> Client modified -- refreshing (x4)client/app.ts (21, 14): Generic type 'Cursor<T>' requires 1 type argument(s).
```

**Comment by barbatus** [comment]
@douglascorrea There is no any data yet added at 3.6 step, so it won't show anything on screen. I guess the issues was that you tried to insert parties from the mongo console after 3.6 but data would not appear. Yes, there is an issue: parties collection is not defined on the server yet at 3.6, so substeps should be rearranged. That what I did in new PR; it should be fixed soon.

@aaronksaunders you can download 3rd step's final source code here https://github.com/Urigo/meteor-angular2.0-socially/archive/step_03.zip. I just checked it works, the problem could be only if you had followed paragraphs directly in the step.
