### ISSUE TITLE
Step 5.8: configure routes (APP_BASE_HREF)

### ISSUE THREAD

**Issue by ysic** [Urigo/meteor-angular2.0-socially#70]
Hi there,
If I'm correct APP_BASE_HREF import location changes from:
import {APP_BASE_HREF } from 'angular2/router';
to
import {APP_BASE_HREF } from 'angular2/platform/common';

And in the text explaining "configure routes" your are using BASE_APP_HREF instead of APP_BASE_HREF

**Comment by Urigo** [comment]
thanks!
Fixed in the new version of the tutorial
