### ISSUE TITLE
Step 8 - doesn't work at all (

### ISSUE THREAD

**Issue by y-vasilyev** [Urigo/meteor-angular2.0-socially#71]
After finising step 8, I got errors with dependenceies

Tryed to run cloned repository - it doesnt work too (
`npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.7 does not satisfy its siblings
' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants rxjs@5.0.0-beta.6
npm ERR! peerinvalid Peer angular2-meteor@0.5.3 wants rxjs@5.0.0-beta.2
npm ERR! peerinvalid Peer ng2-material@0.2.12 wants rxjs@>=5.0.0-beta.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Angular2Meteor\a2m\npm-debug.log`

**Comment by stefanholzapfel** [comment]
@y-vasilyev:
Did you try to update your rxjs package?
ng2-material wants a version greater than beta.2, so it seems you're on a lower version?
Try `"rxjs": "^5.0.0-beta.7"` in your package.json and reinstall that package...

Nevertheless, I also get loads of dependency errors (also got reflect-metadata v 0.1.2 installed):

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\XXXXX\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\bin\\node.exe" "C:\Users\XXXXX\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_mo
dules\npm\bin\npm-cli.js" "install" "--save" "angular2-meteor-accounts-ui"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants reflect-metadata@0.1.2
npm ERR! peerinvalid Peer angular2-meteor@0.5.3 wants reflect-metadata@0.1.2

**Comment by stefanholzapfel** [comment]
Finally got it running without dependency errors with this package versions:

`"dependencies": {`
`"angular2": "^2.0.0-beta.17",`
`"angular2-meteor": "^0.5.4",`
`"angular2-meteor-auto-bootstrap": "^0.5.1",`
`"angular2-meteor-accounts-ui": "^0.3.5",`
`"es6-shim": "^0.35.0",`
`"meteor-node-stubs": "^0.2.3",`
`"reflect-metadata": "0.1.2",`
`"rxjs": "5.0.0-beta.6",`
`"zone.js": "^0.6.10"`
`}`

**Comment by Urigo** [comment]
thanks, we've updated the tutorial yesterday to support latest versions
