### ISSUE TITLE
npm ERR! peerinvalid The package angular2@2.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by p3140** [Urigo/meteor-angular2.0-socially#74]
Hi, when i run meteor npm install on this project, it returns the following errors:

npm ERR! node v0.10.43
npm ERR! npm  v2.15.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular2@2.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2-meteor@0.5.2 wants angular2@2.0.0-beta.12
npm ERR! peerinvalid Peer angular2-meteor-accounts-ui@0.3.5 wants angular2@>=2.0.0-beta.9
npm ERR! peerinvalid Peer angular2-meteor-auto-bootstrap@0.5.1 wants angular2@^2.0.0-beta.17
npm ERR! peerinvalid Peer angular2-pagination@0.1.0 wants angular2@^2.0.0-beta.12
npm ERR! peerinvalid Peer ng2-material@0.2.12 wants angular2@>=2.0.0-beta.11

How can i fix it ?, thanks !

**Comment by andyrue** [comment]
I think the package dependencies are out of date in this repo. Update your package.json file and set your dependencies to the following.

```
"dependencies": {
  "angular2": "^2.0.0-beta.17",
  "angular2-meteor": "^0.5.4",
  "angular2-meteor-auto-bootstrap": "^0.5.2",
  "es6-shim": "^0.35.0",
  "meteor-node-stubs": "^0.2.3",
  "reflect-metadata": "0.1.2",
  "rxjs": "5.0.0-beta.6",
  "zone.js": "^0.6.12"
},
```

That build is working for me.

**Comment by Urigo** [comment]
we've updated all version to the new angular rc and updated the tutorial accordingly
