### ISSUE TITLE
Step 3.7: Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object] (reflective_provider.js:162)

### ISSUE THREAD

**Issue by phund** [Urigo/meteor-angular2.0-socially#76]
Hi,
After I use Blaze-like Binding to Angular in step 3 (with angular2.0.0-rc.1). it raise below error:
`Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object] (reflective_provider.js:162)`

But when I use tracker instead -> it work properly

There are dependencies in  package.json.

> "dependencies": {
>     "@angular/core": "^2.0.0-rc.1",
>     "angular2": "^2.0.0-beta.17",
>     "angular2-meteor": "^0.5.5",
>     "angular2-meteor-auto-bootstrap": "^0.5.4",
>     "es6-shim": "^0.35.0",
>     "reflect-metadata": "^0.1.2",
>     "rxjs": "^5.0.0-beta.6",
>     "zone.js": "^0.6.12"
>   }

Please help me!

**Comment by phund** [comment]
I found a solution to resolve this problem:
1. Change dependencies in package.json to:

```
"dependencies": {
    "@angular/core": "2.0.0-rc.1",
    "angular2-meteor": "https://github.com/Urigo/angular2-meteor",
    "angular2-meteor-auto-bootstrap": "https://github.com/Urigo/angular2-meteor-auto-bootstrap",
    "es6-shim": "^0.35.0",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
```

Change all imports from 'angular2/_' to '@angular/_'
Ex:
`import {Component} from 'angular2/core';`
instead of
`import {Component} from '@angular/core';`

Hope to help someone :). 
Anyone catch this issue and have another solution?

**Comment by ashishpok** [comment]
@phund I got into same issue and the solution worked for me as well. Thanks for the solution. I am guessing some changes in angular2 API is breaking this or needs a new typing map somewhere. Will appreciate if anyone in angular2-meteor team is able to shed some light?

**Comment by ashishpok** [comment]
well, it turns out tutorial and some of the dependent modules (like accounts-ui) needs to be redone for angular2-rc. I could get by most of the chapters with imports of '@angular/*' modules. 

router chapter probably needs to be re-written as it looks like all of the beta router classes are deprecated in rc.

**Comment by Urigo** [comment]
I've updated the tutorial to the latest RC, let me know it everything is working for you now

**Comment by phund** [comment]
@Urigo It worked for me as well now. Thank you.

**Comment by ashishpok** [comment]
@Urigo, thanks !!! So far so good. Also thanks for updating accounts-ui module too, worked fine without needing any mods this time. I am not sure if router chapter is still somewhat incomplete or not. Perhaps just the user injection bits - I made it work implementing a simple checkPermission method.

**Comment by ashishpok** [comment]
Ok, I completely missed you had checkPermissions method right there :) Anyways, I got a little hands on tutorial writing my own - I might have just looked at github code (there were no commits for the Inject users exercise).
