### ISSUE TITLE
STEP 3 EXCEPTION: No Directive annotation found on Socially

### ISSUE THREAD

**Issue by hkashlan** [Urigo/meteor-angular2.0-socially#77]
Hi 
After I replaced
import {bootstrap} from 'angular2/platform/browser';
with 
import {bootstrap} from 'angular2-meteor-auto-bootstrap';

I am getting No Directive annotation found on Socially

BTW I run this command "meteor npm install --save angular2 "

BTW if back to angular2/platform/browser it is work again

**Comment by chinchalupa** [comment]
+1. I have researched a bit as to how to fix this and have come up with no solution. I also have issues when using angular2/platform/browser where ngFor says it only binds to Iterables like arrays.

**Comment by hkashlan** [comment]
Hi I follow these 2 issues
https://github.com/Urigo/meteor-angular2.0-socially/issues/77
https://github.com/Urigo/meteor-angular2.0-socially/issues/78

and I fixed my problem

**Comment by Urigo** [comment]
I've updated the tutorial to fix this issue
