### ISSUE TITLE
Step 0.6: Dependencies missing, wrong import statements (RC1 now!)

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/meteor-angular2.0-socially#78]
@Urigo 
In the new angular-meteor package, the dependency has changed to Angular 2 RC1 and therefore also the import statements have changed, which has not been reflected in the tutorial.

I hope this is correct, at least it's working for me:

Step 0.6:
Change
`import {Component} from 'angular2/core';`
`import {bootstrap} from 'angular2/platform/browser';`
to
`import {Component} from '@angular/core';`
`import {bootstrap} from '@angular/platform-browser-dynamic';`

Additionally you have to declare these dependencies in your package.json and install them. Seems angular packages are now modular (what makes sense for production):
`"@angular/core": "^2.0.0-rc.1",`
`"@angular/platform-browser-dynamic": "^2.0.0-rc.1",`
`"@angular/common": "^2.0.0-rc.1",`
`"@angular/compiler": "^2.0.0-rc.1",`

**Comment by Urigo** [comment]
thanks for the heads up!
I've just finished updating the tutorial to the latest rc.
please let me know if it's working for you
