### ISSUE TITLE
RsvpPipe not working correctly 

### ISSUE THREAD

**Issue by p3140** [Urigo/meteor-angular2.0-socially#79]
In RsvpPipe i need to do 
`export class RsvpPipe extends MeteorComponent {
    init: Array = [];
    total: number = 0;`

and then 
`this.init[party._id] = true;`

In other hand, this.autorun() doesn't get executed the first time that the page is loaded, it just work after clicking on "Edit" and then going back.

**Comment by Urigo** [comment]
@p3140 can you check now with the new version of the tutorial?

**Comment by kaihaase** [comment]
I found another error in the RsvpPipe:
`transform(party: Party, args: any[]): number {
    let type = args[0]; ...`
That leads to the fact that only the first letter of "yes", "maybe" or "no" is stored in the variable `type` and the evaluation in the filter does not work .
My suggestion:
`transform(party: Party, type: string): number { ...`

**Comment by kamilkisiela** [comment]
@kaihaase Yes, there was a breaking change with Angular2 RC1. I will fix it soon.

**Comment by kamilkisiela** [comment]
#98 should fix it
