### ISSUE TITLE
Step 2.1: Code changes not reflected in explanation

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/meteor-angular2.0-socially#80]
@Urigo 
In the 2.1 code template the depcrecated "#" syntax for local scope variables has been replaced with the let keyword, but in the explanation below it's still *ngFor="#party of parties". That could irritate people who are just starting off.

Additionally in step 2.3 row 11:
Better use  `parties: Array<Object>;` instead of `parties: Array;` to avoid error message due to generic type of Array?

**Comment by Urigo** [comment]
updated and fixed.
thanks for the heads up!
