### ISSUE TITLE
Upgrade it to Angular2 - Release candidate "2.0.0-rc.1"

### ISSUE THREAD

**Issue by RohitLuthra19** [Urigo/meteor-angular2.0-socially#81]
**Hi,**
Please can you upgrade it to Angular2 - Release candidate "2.0.0-rc.1"

Because i think you code is written beta version but there are many changes occurred from beta to rc.1 
And some of the changes i saw in Angular2 Routing 
1. @RouteConfig now @Routes
2. **RouteParams *_now *_RouteSegment**

**Comment by Urigo** [comment]
I've updated the tutorial to the latest RC now.
I'm using the old router but with the new import, I'm not sure what are the breaking changes in the new router
