### ISSUE TITLE
Step 4.9: You have to cast to "Control"

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/meteor-angular2.0-socially#82]
In 4.9 line 31-33 you have to cast the controls to "Control" because otherwise the compiler recognizes it as an "AbstractControl", which has no updateValue property.

e.g.:

`(<Control>this.partiesForm.controls['name']).updateValue('');`
instead of
`(this.partiesForm.controls['name']).updateValue('');`

And don't forget to import Control (from @angular/common when youre on RC1)!
`import {FormBuilder, ControlGroup, Validators, Control} from '@angular/common';`

**Comment by Urigo** [comment]
Thanks for the help!
fixed in the new version of the tutorial
