### ISSUE TITLE
No Directive annotation found on Socially - Step 3 of the angular2-meteor tutorial

### ISSUE THREAD

**Issue by dean0x** [Urigo/meteor-angular2.0-socially#83]
Hi Guys, new to angular and meteor, following the tutorial after completing step 3 I get the following error in the console

No Directive annotation found on Socially

this guy gets the same error as well:

http://stackoverflow.com/questions/37149260/angular-meteor-error-with-angular2-meteor-auto-bootstrap-no-directive-annota

tried to solve it by adding this code to app.ts but it didn't work:

import {Directive} from '@angular2/core'

@Directive ({ selector: app })

Any ideas?

**Comment by hongbo-miao** [comment]
Hi @dean0x I explained a little bit in [Meteor forum](https://forums.meteor.com/t/for-people-who-are-following-socially-tutorial-and-met-problems/22994). See whether it helps.

**Comment by pivie** [comment]
I followed the instructions on the forum and also did npm install --save @angular/compiler and it works now. Thank you!

**Comment by Urigo** [comment]
thanks for the input, I've updated the tutorial to support the latest rc

**Comment by dean0x** [comment]
Thanks for the quick fix and for the helpful tutorial!
