### ISSUE TITLE
Cannot find module '@angular2/core' (npm 3.9.0, node 6.10) - latest tutorial version

### ISSUE THREAD

**Issue by dragGH102** [Urigo/meteor-angular2.0-socially#84]
Today I started the official tutorial from scratch.
However it doesn't work:

> Cannot find module '@angular2/core'

I tried by

> meteor npm install --save @angular2 @angular

but

> could not install <project-dir> /@angular2

I tried to download the latest version of node (6.10). It came bundled with npm 3.8.6.

I updated npm to **3.9.0.** by

> sudo npm -g install npm

but still same issue.
Anyone with the same issue? any clue?

**Comment by borgellaj** [comment]
I made it all the way through chapter 5 and it wont run as well. getting errors 

```
client/imports/parties-form/parties-form.ts (1, 31): Cannot find module 'angular2/core'.
client/imports/parties-form/parties-form.ts (3, 62): Cannot find module 'angular2/common'.
client/imports/parties-form/parties-form.ts (5, 23): Cannot find module 'collections/parties'.
client/imports/parties-list/parties-list.ts (14, 12): Generic type 'Cursor<T>' requires 1 type argument(s).
collections/parties.ts (1, 26): Cannot find name 'Mongo'.
parties-list.ts (2, 29): Cannot find module '../../../collections/parties'.
parties-list.ts (3, 29): Cannot find module '../parties-form/parties-form'.
parties-list.ts (12, 12): Generic type 'Cursor<T>' requires 1 type argument(s).
```

**Comment by dragGH102** [comment]
@borgellaj good to see I'm not the only one with the error.

As for

> parties-list.ts (12, 12): Generic type 'Cursor' requires 1 type argument(s).

I think it's about the typings because when I actually try to set <Object> after Cursos it says it's not a generic.

**Comment by borgellaj** [comment]
Well hopefully this issue gets resolved real soon. I see a lot of promise in the platform

**Comment by Urigo** [comment]
it might be because I've updated the tutorial when you were in the middle?

Can you try to start from scratch now and see if it works?

**Comment by borgellaj** [comment]
I started from scratch yesterday. Ill do it again.

**Comment by dragGH102** [comment]
same here.
I tried from scratch just a couple of days ago.i think you updated the
tutorial around 1 week ago. didn't you?

@urigo
will retry next days If you can confirm the tutorial if all fine at least
up to step 3.
can you please just day which node / npm versions do you use?

**Comment by ijager** [comment]
Your Mongo.Cursor object needs a type parameter like this:

`parties: Mongo.Cursor<Object>;`

or

`parties: Mongo.Cursor<any>;`

edit: In Step 7 it is explained I see now

**Comment by kamilkisiela** [comment]
There is a new version of Socially2.0. It seems like this is issue has been fixed. Please reopen if it still occurs.
