### ISSUE TITLE
<Control> cast rendered as html

### ISSUE THREAD

**Issue by ijager** [Urigo/meteor-angular2.0-socially#85]
In code snippet [4.9](https://github.com/Urigo/meteor-angular2.0-socially/commit/babd9af380a28c6a192cf381a3b7d48173406d7e) the cast to `<Control>` is interpreted as an html tag in the [website](http://www.angular-meteor.com/tutorials/socially/angular2/adding-removing-objects-and-angular-event-handling)

**Comment by Urigo** [comment]
fixed
