### ISSUE TITLE
 Generic type 'Cursor<T>' requires 1 type argument(s) in Step 5.2

### ISSUE THREAD

**Issue by qbolec** [Urigo/meteor-angular2.0-socially#88]
I do not know how to propose suggestions to the diffboxes, but there is a bug in 5.2 Create PartiesList component, namely:

```
parties: Mongo.Cursor;
```

should be changed to

```
parties: Mongo.Cursor<Object>;
```

to prevent errors like:

```
client/imports/parties-list/parties-list.ts (12, 12): Generic type 'Cursor<T>' requires 1 type argument(s).
```

and to maintain the promise that we are simply moving "the content of Socially in app.ts out into a PartiesList component"

**Comment by kamilkisiela** [comment]
Totally agree, I'll update it soon :+1:
