### ISSUE TITLE
The /party/:id does not handle F5 after step 5

### ISSUE THREAD

**Issue by qbolec** [Urigo/meteor-angular2.0-socially#90]
After finishing Step 5, the app seems to work as long as I start from the `/` url and navigate within it, but as soon as I press F5, while being on a subpage, it stops working (shows empty white screen without any error message).
This also affects the hot reload caused by editing code (say: during 5.14 one is asked to change the details page, and after I actually do change it, the page "vanishes" which is confusing).

One more thing: It might be the case that I did something wrong, so to make sure my local version of code is the same as in tutorial I've tried to download the zip file from the begining of Step 6. It turns out that the code inside the zip is mostly different than the code in tutorial. In particular the client/app.ts in the zip file starts with:

``` ts
import {Component, View, NgZone, provide} from 'angular2/core';
```

while the version in tutorial starts with `import 'reflect-metadata';`.

**Comment by qbolec** [comment]
I believe that the problem might be caused by the line:

```
templateUrl: 'client/app.html',
```

in diffbox 5.8. Perhaps this path should start with a slash?
After prepending the slash, it still does not work, but at least now I see an error message:

```
EXCEPTION: Error in /client/imports/party-details/party-details.html:1:6
ORIGINAL EXCEPTION: TypeError: Cannot read property 'name' of undefined
```

**Comment by qbolec** [comment]
This seems to be caused by `Parties.findOne(partyId)` returning `undefined` when the subpage is refreshed, as opposed to an Object instance when the subpage is simply navigated to from the main page.

**Comment by qbolec** [comment]
After an hour of voodoo-programming I've managed to guess the incantation which works:

``` ts
import { Component } from '@angular/core';
import { RouteParams } from '@angular/router-deprecated';
import { Parties, IParty } from '../../../collections/parties.ts';
import {MeteorComponent} from 'angular2-meteor';

@Component({
  selector: 'party-details',
  templateUrl: '/client/imports/party-details/party-details.html'
})
export class PartyDetails extends MeteorComponent{
    party: IParty;
    partyId: string;
    constructor(params: RouteParams) {
        super();
        this.partyId = params.get('partyId');
        this.autorun(()=>{
            this.party = Parties.findOne(this.partyId) || {location:"loading",description:"please wait",name:"loading"};
        },true)
    }
}
```

It looks like removing `,true` from the `this.autorun` call arguments breaks it, so I guess it is required for some reason.

**Comment by qbolec** [comment]
I've tried to replace `this.autorun` with `Tracker.autorun` and while it did update `this.party`, it fails to update the HTML view, so there is definitely something important about "running in the zone", but I do not know what "the zone is" yet :(

**Comment by kamilkisiela** [comment]
Tutorial has been updated. It seems to work fine now :)

New version of Angular2 has arrived :bullettrain_side: , you should try it! :+1:

**Comment by kaihaase** [comment]
I've tried it with the latest versions of all packages and the actual tutorial, but the problem is still the same: white page after reload a subpage (like @qbolec wrote)

**Comment by simonv3** [comment]
This is probably related to: https://github.com/Urigo/angular-meteor-docs/issues/137

Can you try the fix I suggest there?

**Comment by qbolec** [comment]
I'm not sure if @simonv3 question is addressed to me, but : 
1. the link to SO seems not to link to any specific answer, but rather to the question, so it's not clear to me to which of the answers you had in mind
2. if you mean the accepted answer, then it is not clear to me how to use nginx or live-server to solve this issue - I'm almost sure that I run the tutorial by simply typing `meteor`
3. as indicated by my first few posts in this thread I think there are two issues to solve here: 
- the first issue is that the page is blank, and this one seems connected to the way relative paths of `templateUrl`s are resolved during imports (which in turn might be connected to routing on server-side or client-side, but this step of inference is beyond my understanding of Meteor inner workings) and I was able to resolve this problem by simply prepending a leading slash to `templateUrl`. I have not tried solutions from SO, but I believe they are aimed at this issue. 
- the second issue is that `collection.findOne(...)` might return `undefined` if called too early, and thus one have to either wait till the collection is initialized before rendering, or make the component able to handle `undefined` and autorun again one the collection is ready. I was not able to solve this issue by following the first path, as I could not guess a correct way of delaying the rendering untill the `Meteor.subscribe`'s callback. I did however solve the problem by following the other path, which was to put updating of `this.party` into `this.autorun` and using some dummy data before it is loaded.

I'm not 100% sure, but from what I recall the URL in the address bar of my browser did contain a hash sign, which to me indicates, that the problem isn't in the server-side routing, but who knows.

**Comment by simonv3** [comment]
@qbolec It was directed at anyone who was experiencing this problem, cause I was experiencing it too and this answer fixed it for me: http://stackoverflow.com/a/35052147/154392 (sorry, fixed the link here and on the other issue). This aligns with what you did to fix it - prepend with a "/". 

The URL in my address bar didn't contain a '#' after following the tutorial, but maybe I missed a step.

**Comment by kamilkisiela** [comment]
try to change [this](https://github.com/Urigo/meteor-angular2.0-socially/blob/master/client/app.ts#L28):

``` ts
@Component({
  selector: 'app',
  templateUrl: 'client/app.html',
```

to:

``` ts
@Component({
  selector: 'app',
  templateUrl: '/client/app.html', // the change
```

so `/client/app.html` instead of `client/app.html`.

Otherwise it tries to load `http://localhost:3000/party/client/app.html` which doesn't exist so it returns whole new <html> with an app.

**Comment by kamilkisiela** [comment]
There might be no subscription with Parties Collection ready so we also have to make it reactive.

``` ts
// client/app.ts:
import { Component, NgZone } from '@angular/core';
import { RouteParams } from '@angular/router-deprecated';
import { Tracker } from 'meteor/tracker';
import {Parties} from '../../../collections/parties.ts';

@Component({
  selector: 'party-details',
  templateUrl: '/client/imports/party-details/party-details.html'
})
export class PartyDetails {
  party: Object;

  constructor(params: RouteParams, ngZone: NgZone) {
    var partyId = params.get('partyId');

    Tracker.autorun(() => { // reactive
      ngZone.run(() => { // run inside Angular2 world
        this.party = Parties.findOne(partyId);
      });
    });
  }
}
```

**Comment by elmendavies** [comment]
Dear kamilkisiela:  Thank you. It solved my issue too. If it could be improved, it is probably better to derive PartyDetails from the MeteorComponent to call MeteorComponent.autorun. The full file is:

```
import { Component, NgZone } from '@angular/core';
import { RouteParams, RouterLink } from '@angular/router-deprecated';
import { Parties } from '../../../collections/parties';
import { MeteorComponent } from 'angular2-meteor';

@Component({
    selector: 'party-details',
    templateUrl: '/client/imports/party-details/party-details.html',
    directives: [ RouterLink ]

export class PartyDetails extends MeteorComponent { 
    party: Object;

    constructor(private params: RouteParams, ngZone: NgZone) {
        super();
        var partyId = params.get('partyId');

        this.autorun(() => { // reactive
            ngZone.run(() => { // run inside Angular2 world
                this.party = Parties.findOne(partyId);
            });
        });

    }

    saveParty(party) {
        Parties.update(party._id, {
            $set: {
                name: party.name,
                description: party.description,
                location: party.location
            }
        });
    }
}
```

**Comment by kamilkisiela** [comment]
@elmendavies Sure, it is better.

You can even use it like this with `MeteorComponent`:

``` ts
this.autorun(() => {
  this.party = Parties.findOne(partyId);
}, true);
```

I made it with usage of `Tracker.autorun` and `ngZone.run` because `MeteorComponent` is being introduced in one of next chapters.

**Comment by qbolec** [comment]
I don't want to be rude, but what is exactly the difference between the solutions proposed by you, and the solution proposed by myself in https://github.com/Urigo/meteor-angular2.0-socially/issues/90#issuecomment-220065418

**Comment by sunshineo** [comment]
Hello everyone. Why is this closed? I installed the latest meteor, git cloned the latest code of this repository and still have the same problem. A little different now that it is not a completely empty page. It has the banner with login and sign up. But still no party details.
![sociallyblank](https://cloud.githubusercontent.com/assets/1072766/15763059/3361d77a-28d6-11e6-979d-032e26f3fc3a.jpg)
