### ISSUE TITLE
Steps to step 20 (a.k.a. file storage)

### ISSUE THREAD

**Issue by dinigo** [Urigo/meteor-angular2.0-socially#92]
I know it's not yet submited. But I happen to need a file storage and this solution seems to be the best.

So far it fails when I try to import the library like this:

``` js
import {UploadFS} from 'meteor/jalik:ufs'
```

The error thrown sais it couldn't find the library (on the client side). 

I thought it may be because the library is in `js` while the rest of the project in `ts` so I tried to write a stub `ufs.d.ts`, first by hand, then with [dtsmake](https://github.com/ConquestArrow/dtsmake), and then at hand again when I found I had to export the module `UploadFS` so that meteor (barbatus:typescript?) could see it:

``` js
declare module 'meteor/jalik:ufs' {
    export module UploadFS{
        interface UploadFS {
            ...
        }
    }
}
```

So far I had my `ufs.d.ts` stub file at the `typings/` folder and linked in the `main.d.ts`. No errors at compile time. Meteor sad the DB was correctly created ... but then when I tried to use it broke.

I found that UploadFS was undefined so I supposed it wasn't referencing the library even though it compiled to js allright.

So I suppose the only thing I've have left is to translate `jalik:ufs` and `jalik:ufs-gridfs` to typescript by hand. Is that correct? Is there an easier way of making ufs work wit angular2-meteor?

---

PS: I submited it also to [stackoverflow ](http://stackoverflow.com/q/37339580/621058)

**Comment by kamilkisiela** [comment]
@demil133 

``` ts
import { UploadFS } from 'meteor/jalik:ufs';
console.log('UploadFS', UploadFS);
```

This gives me the `UploadFS` object and I think it's totally independent of `angular2-meteor` so I suppose that `jalik:ufs` should be working fine, even with those warnings generated by ts compiler.

About typings, those warning are very annoying, I know :smiley: but you can pretend you don't see them for now.

Here's an example implementation of `jalik:ufs` I made for Angular1, but it will look pretty much the same with Angular2.

http://www.angular-meteor.com/tutorials/socially/angular1/handling-files-with-collectionfs

**Comment by kamilkisiela** [comment]
@demil133 You can track changes here #102 :+1: 

I'm working on 20th chapter so _upload is coming_ :snowflake:

**Comment by kamilkisiela** [comment]
Done
