### ISSUE TITLE
"meteor run ios" shows a blank page

### ISSUE THREAD

**Issue by sunshineo** [Urigo/meteor-angular2.0-socially#93]
I'm following the tutorial.
My socially app runs properly in browser.
However when run it in ios simulator it just shows a blank page.
I inspected the cordova build and it shows no js file I expected to build from the ts files.
I downloaded this project https://github.com/Urigo/meteor-angular2.0-socially and it is the same thing.
If this is still work in progress, I think we need to indicate this in the tutorial.

![nojsfiles](https://cloud.githubusercontent.com/assets/1072766/15626064/bdbd53c4-246f-11e6-83fd-91470cfa17b8.jpg)

**Comment by MichaelSolati** [comment]
I have essentially had the same issue in a few places, both on iOS and android (Native) after I use phonegap.

**Comment by MichaelSolati** [comment]
Some logs from Android if they help...

```
I20160608-20:29:05.394(-4)? 06-08 20:29:00.739  3614  3614 I chromium: [INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0, default verbosity = 0
I20160608-20:29:05.656(-4)? 06-08 20:29:00.955  3614  3614 W chromium: [WARNING:resource_bundle.cc(285)] locale_file_path.empty()
I20160608-20:29:05.657(-4)? 06-08 20:29:01.604  3614  3639 W chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
I20160608-20:29:05.657(-4)? 06-08 20:29:02.346  3614  3614 I MeteorWebApp: Serving asset bundle with version: 2c0134192e15d24dd416bf3e83e764eed3d5470e
I20160608-20:29:07.513(-4)? 06-08 20:29:06.769  3614  3649 E chromium: [ERROR:buffer_manager.cc(340)] [GroupMarkerNotSet(crbug.com/242999)!:7CF8839C]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
I20160608-20:29:08.625(-4)? 06-08 20:29:07.882  3614  3614 I chromium: [INFO:CONSOLE(114003)] "Uncaught TypeError: Cannot read property 'appendChild' of null", source: http://localhost:12352/packages/modules.js?hash=e127e8728c2a46cdd35385b3ce92cfe62ef1ffda (114003)
I20160608-20:29:08.672(-4)? 06-08 20:29:07.930  3614  3614 I chromium: [INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source: http://localhost:12352/cordova.js (1185)
```

**Comment by barbatus** [comment]
this seems to be resolved

**Comment by sunshineo** [comment]
Hello, this is not resolved for me. Here is what I did

// update my meteor to lates
curl https://install.meteor.com/ | sh
// clone this project
git clone https://github.com/Urigo/meteor-angular2.0-socially
cd meteor-angular2.0-socially
// do a meteor update
meteor update
// install npm packages
meteor npm install 
// start it
meteor add-platform ios
meteor run ios

I got a blank page.

**Comment by kamilkisiela** [comment]
This blank page is because of an known issue justindujardin/ng2-material#257

I also created a PR for that justindujardin/ng2-material#260

About that missing js file. There won't be any because every js file is bundled into `app.js`.

Related issue #107
