### ISSUE TITLE
Safari report error

### ISSUE THREAD

**Issue by oliverwy** [Urigo/meteor-angular2.0-socially#99]
when I run in Safari,get a white page.I open the console,find these error messages.
I'am sorry ,the following is :

```
browser_adapter.js:77EXCEPTION: RangeError: Maximum call stack size exceeded. 

[Error] EXCEPTION: RangeError: Maximum call stack size exceeded.
    logError (modules.js:60218)
    logGroup (modules.js:60228)
    call (modules.js:49631)
    （匿名函数） (modules.js:55075)
    invoke (modules.js:45327)
    onInvoke (modules.js:55496)
    invoke (modules.js:45326)
    run (modules.js:45220)
    runInner (modules.js:55527)
    run (modules.js:55419)
    run (modules.js:55064)
    coreLoadAndBootstrap (modules.js:54870)
    （匿名函数） (modules.js:87543:85)
    （匿名函数） (modules.js:87533)
    withValue (meteor.js:1077)
    （匿名函数） (modules.js:87532)
    maybeReady (meteor.js:809)
    loadingCompleted (meteor.js:821)
```

**Comment by oliverwy** [comment]
Before add the Angularjs2 ,The app is OK ,After I execute the command:
 meteor add angular2-compilers barbatus:angular2-runtime
meteor npm install --save angular2-meteor @angular/platform-browser-dynamic
then finish the rest of Step 0 - Bootstrapping.

run app

the white blank page come.

but Chrome and Firefox is OK ,only the  Safari get the blank page.

**Comment by MichaelSolati** [comment]
Try removing `import 'zone.js/dist/zone';` from app.ts

**Comment by hongbo-miao** [comment]
I think now install angular2-meteor-polyfills will help now.
Refer to https://github.com/Urigo/angular2-meteor/issues/273

**Comment by barbatus** [comment]
Please update `barbatus:angular2-runtime` to 0.5.0 and run `npm install angular2-meteor-polyfills`

**Comment by oliverwang07** [comment]
thank everyone,Now it's OK!
